
//                  !! RAM !!

/**
 * SQLEditorPanel.java
 *
 * Created on October 30, 2007, 6:17 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor;

/***
 *
 * @author  sumit
 */
public class SQLEditorPanel extends javax.swing.JPanel  implements org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface {
    
    /*** Creates new form SQLEditorPanel */
    public SQLEditorPanel( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        this.Engine = Engine;
        this.SQLEditor = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditor( this.Engine.getIOManager() );
        initComponents();        
        this.addEditor();
    }
    
    private final void addEditor(){
        javax.swing.JScrollPane Pane = new javax.swing.JScrollPane( this.SQLEditor );
        super.add( Pane );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        CompileBtn = new javax.swing.JButton();
        ExecuteBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        CompileBtn.setText("Compile");
        CompileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompileBtnActionPerformed(evt);
            }
        });

        ExecuteBtn.setText("Execute");
        ExecuteBtn.setEnabled(false);

        ClearBtn.setText("Clear");
        ClearBtn.setEnabled(false);
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CompileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExecuteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearBtn)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompileBtn)
                    .addComponent(ExecuteBtn)
                    .addComponent(ClearBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(jPanel1, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents

    private void CompileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompileBtnActionPerformed
        String Mess = this.Engine.compileProcedure( this.SQLEditor.getText() );
         if( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
            onCompilation();
            javax.swing.JOptionPane.showMessageDialog( this, "Procedure was successfully compiled","Procedure Compiled Successfully", javax.swing.JOptionPane.INFORMATION_MESSAGE );
        }
        else{
            javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ),"Procedure Compiled Failure", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_CompileBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        this.SQLEditor.setText( null );
    }//GEN-LAST:event_ClearBtnActionPerformed
    
         
    public org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.Edit.DocEditActionProvider getActionProvider(){
        return this.SQLEditor.getActionProvider();
    }
    
    public org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.File.FileManager getManager(){
        return this.SQLEditor.getFileManager();
    }
    
    private final void onCompilation(){
        this.CompileBtn.setEnabled( false );
        this.ExecuteBtn.setEnabled( true );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton CompileBtn;
    private javax.swing.JButton ExecuteBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    // editor
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditor SQLEditor = null;
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
}
