
//                                 !! RAM !!

/**
 * addForeignKeyForm.java
 *
 * Created on October 15, 2007, 5:05 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

/***
 *
 * @author  sumit 
 */
public class addForeignKeyForm extends javax.swing.JDialog {
    
    /*** Creates new form addForeignKeyForm */
    public addForeignKeyForm(java.awt.Frame parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseInterface d , String table ) {
        super(parent, true );
        this.Db = d;
        this.Tb = table;
        initComponents();
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel3;
        javax.swing.JLabel jLabel4;
        javax.swing.JLabel jLabel5;
        javax.swing.JLabel jLabel6;
        javax.swing.JLabel jLabel7;
        javax.swing.JLabel jLabel9;

        jLabel4 = new javax.swing.JLabel();
        ReferredTables = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ReferredColl = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        onDelete = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        onUpdate = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ForKeyText = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        defer = new javax.swing.JComboBox();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("addForeignKey");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel4.setText("Referred Table");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        this.setReferredTables();
        ReferredTables.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReferredTablesItemStateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(ReferredTables, gridBagConstraints);

        jLabel5.setText("Referred Collumn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        this.setReferredColumn();
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(ReferredColl, gridBagConstraints);

        jLabel6.setText("onDelete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        this.onDelete.addItem ( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeySetDefault);
        this.onDelete.addItem(org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyNoAction);
        this.onDelete.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyCascade);
        this.onDelete.addItem (org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeySetNull);
        this.onDelete.addItem (org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyRestrict);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(onDelete, gridBagConstraints);

        jLabel7.setText("onUpdate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 7, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        this.onUpdate.addItem ( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeySetDefault);
        this.onUpdate.addItem ( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyNoAction);
        this.onUpdate.addItem ( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyCascade);
        this.onUpdate.addItem ( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeySetNull);
        this.onUpdate.addItem ( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyRestrict);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(onUpdate, gridBagConstraints);

        jLabel9.setText("References");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        jLabel3.setText("Foreign Key Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(ForKeyText, gridBagConstraints);

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        getContentPane().add(addbtn, gridBagConstraints);

        cancelbtn.setText("CANCEL");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        getContentPane().add(cancelbtn, gridBagConstraints);

        jLabel1.setText("Deferability");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        this.defer.addItem(                    org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyInitiallyDeferred);

        this.defer.addItem(                    org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyInitiallyImmediate );

        this.defer.addItem(                    org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key.importedKeyNotDeferrable);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        getContentPane().add(defer, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReferredTablesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReferredTablesItemStateChanged
        this.setReferredColumn();
    }//GEN-LAST:event_ReferredTablesItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.onFormCancel();
    }//GEN-LAST:event_formWindowClosed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        this.onFormCancel();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        this.onFormSubmit();
    }//GEN-LAST:event_addbtnActionPerformed
    
    public void setVisible( boolean d){
        // do nothing
    }
    
    public final boolean display(){
        super.setVisible( true );
        return state;
    }
    
    private final void onFormCancel(){
        super.setVisible( false );
    }
    
    private final void onFormSubmit(){
        this.state = true;
        super.setVisible( false );
    }
    
    private final void setReferredTables(){
        org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table[] Tb = Db.getTables();
        
        if( Tb == null || Tb.length < 1 ){           
            return;
        }
        
        for( int i=0 ;i<Tb.length; i++ ){
            this.ReferredTables.addItem( Tb[i].getName() );
        }       
    }// func ends
    
    private final void setReferredColumn(){        
        
        String T = ( String )this.ReferredTables.getSelectedItem();
        this.ReferredColl.removeAllItems();   
        
        org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table[] Tb = Db.getTables();
        
        if( T == null )
            return;
        
        for( int i=0 ; i<Tb.length; i++ ){            
            if( Tb[i].getName().equals( T ) ){                
               org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] Keys = Tb[i].getAttributes();
               
               // find primary key in Keys n add it
               for( int j=0;j< Keys.length; j++ ){
                   if( Keys[j].getAttKey() == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute.PRIMARY_KEY )
                       this.ReferredColl.addItem( Keys[j].getAttName() );
               }
               break;
            }
        }
        
    }// func ends
        
    public final org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyChangeInterface getForeignKeyAddEvent(){
        return ( new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.addForeignKeyForm.ForeignKeyAddEvent() );
    }
    
    /***
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addForeignKeyForm(new javax.swing.JFrame(), null, null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ForKeyText;
    private javax.swing.JComboBox ReferredColl;
    private javax.swing.JComboBox ReferredTables;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox defer;
    private javax.swing.JComboBox onDelete;
    private javax.swing.JComboBox onUpdate;
    // End of variables declaration//GEN-END:variables
    
    private boolean state = false;
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseInterface Db =null;
    private String Tb = null;
    
    
    private class ForeignKeyAddFormConverer implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface {
    
    public String getAttName(){
        return ForKeyText.getText();
    }
        
    public String getPK_Name(){
        return ReferredColl.getSelectedItem().toString();
    }
    
    public String getPk_Database(){ // not necessary
        return Db.getName();
    }
    
    public String getPk_Table(){
        return ReferredTables.getSelectedItem().toString();
    }
    
    public String getUpdate_Rule(){
        return onUpdate.getSelectedItem().toString();
    }
    
    public String getDelete_Rule(){
        return onDelete.getSelectedItem().toString();
    }
    
    public String getDeferability_Rule(){
        return defer.getSelectedItem().toString();
    }
    
    }
    
    private class ForeignKeyAddEvent implements  org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyChangeInterface{
          
               public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface getNewForeignKey(){
                   return ( new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.addForeignKeyForm.ForeignKeyAddFormConverer() );
               }
               
               public String getChangedTable(){                   
                   return Tb;
               }
               
               /**
                * not use full
                */
               public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface getChangedForeignKey(){
                    return null;
                }
                
    }// class ends
}
