
//                         !! RAM !!

/**
 * addTriggerForm.java
 *
 * Created on October 16, 2007, 4:07 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

/***
 *
 * @author  sumit
 */
public class addTriggerForm extends javax.swing.JDialog{
    
    /*** Creates new form addTriggerForm */
    public addTriggerForm(java.awt.Frame parent, boolean modal, String T, String Db ) {
        super(parent, modal);
        this.Table = T;
        this.Database = Db;
        initComponents();
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel3;
        javax.swing.JLabel jLabel4;
        javax.swing.JLabel jLabel5;
        javax.swing.JLabel jLabel6;
        javax.swing.JLabel jLabel7;
        javax.swing.JLabel jLabel8;
        javax.swing.JLabel jLabel9;
        javax.swing.JScrollPane jScrollPane1;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TrigName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TrigTime = new javax.swing.JComboBox();
        TrigEvt = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        TrigCond = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TrigOpr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        OldRefer = new javax.swing.JTextField();
        NewRefer = new javax.swing.JTextField();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("add New Trigger");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Trigger Info");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 12, 0);
        getContentPane().add(TrigName, gridBagConstraints);

        jLabel3.setText("Trigger Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Trigger Event");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        this.TrigTime.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.AFTER);
        this.TrigTime.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.BEFORE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 0);
        getContentPane().add(TrigTime, gridBagConstraints);

        TrigEvt.addItem(  org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.INSERT  );
        TrigEvt.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.DELETE  );
        TrigEvt.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.UPDATE  );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 0);
        getContentPane().add(TrigEvt, gridBagConstraints);

        jLabel5.setText("Trigger Condition");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        TrigCond.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 9, 0);
        getContentPane().add(TrigCond, gridBagConstraints);

        TrigOpr.setColumns(20);
        TrigOpr.setFont(new java.awt.Font("Monospaced", 1, 18));
        TrigOpr.setRows(5);
        jScrollPane1.setViewportView(TrigOpr);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel6.setText("Operation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(27, 10, 2, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel7.setText("Reference Variable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Old");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("New");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        OldRefer.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(OldRefer, gridBagConstraints);

        NewRefer.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(NewRefer, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.onFormCancel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.onFormSubmit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.onFormCancel();
    }//GEN-LAST:event_formWindowClosed
    
    
    public void setVisible( boolean t ){
        // do nothing
    }
    
    public boolean display(){
        super.setVisible( true );
        return this.state;
    }
    
    public void onFormSubmit(){
       this.state = true;
       super.setVisible( false );
    }
    
    public void onFormCancel(){
        super.setVisible( false );
    }
    
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TriggerChangeInterface getTriggerAdditionEvent(){
        return ( new TriggerAdditonEvent() );
    }
    
    
    /***
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTriggerForm(new javax.swing.JFrame(), true, null, null ).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewRefer;
    private javax.swing.JTextField OldRefer;
    private javax.swing.JTextField TrigCond;
    private javax.swing.JComboBox TrigEvt;
    private javax.swing.JTextField TrigName;
    private javax.swing.JTextArea TrigOpr;
    private javax.swing.JComboBox TrigTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
    
    private boolean state = false;
    private String Table = null;
    private String Database = null;
    
    
    private class TriggerFormConverter  implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableTriggerInterface{
    
    public String getCondition(){
        return TrigCond.getText();
    }

    public String getEvent(){
        return TrigEvt.getSelectedItem().toString();
    }

    public String getName(){
        return TrigName.getText();
    }

    public String getOperation(){
        return TrigOpr.getText();
    }

    public String getTiming(){
        return TrigTime.getSelectedItem().toString();
    }
    
    
    public String getOldReference(){
        return OldRefer.getText();
    }
    
    public String getNewReference(){
        return NewRefer.getText();
    }    
    
    }// class emds
    
    private class TriggerAdditonEvent implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TriggerChangeInterface {
        
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableTriggerInterface getChangedTrigger(){
        return null;// not usefull
    }
    
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableTriggerInterface getNewTrigger(){
        return ( new TriggerFormConverter() );
    }
    
    public String getChangedTableName(){
        return Table; 
    }

    public String getTriggerDatabase(){
        return Database;
    }
    
    }
    
}
