
//                          !! RAM !!

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

import org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute;

/**
 * Create_New_Table.java
 *
 * Created on July 7, 2007, 3:06 PM
 */

/***
 *
 * @author  sumit
 */
public class Create_New_Table extends java.awt.Dialog //implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableInterface
{
    
    /*** Creates new form Create_New_Table */
    public Create_New_Table(java.awt.Frame parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.DatabaseReader d ) {
        super(parent, true );
        this.DbRead = d;
        initComponents();        
        super.setLocationRelativeTo( null );
    }

    private void addTypes() {
        String[] list = this.DbRead.getSupportedTypesList();
        if( list != null ){
            for( int i=0 ;i< list.length; i++){
                this.AttTypeCombo.addItem( list[i] );
            }
        }
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JPanel jPanel2;
        javax.swing.JPanel jPanel3;
        javax.swing.JTabbedPane jTabbedPane2;
        javax.swing.JToolBar jToolBar1;

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CommentText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TypeCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        RowFormatCombo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        DatabaseCombo = new javax.swing.JComboBox();
        // THIS COMBO BOX IS USED TO SHOW ONLY THE DATABASES OF WHICH THSI TABLE IS A PART OF SO HERE THE CODE MUST BE WRITTE TO ADD THE DATAABASE MAMES
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CollNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CollLengthText = new javax.swing.JTextField();
        CollDefaultText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CollExtraValText = new javax.swing.JTextField();
        PrimaryKeyCheck = new javax.swing.JCheckBox();
        ForeignKeyCheck = new javax.swing.JCheckBox();
        IndexCheck = new javax.swing.JCheckBox();
        CompulsoryCheck = new javax.swing.JCheckBox();
        Incrementcheck = new javax.swing.JCheckBox();
        zerofillcheck = new javax.swing.JCheckBox();
        Signedcheck = new javax.swing.JCheckBox();
        addCollumnsBn = new javax.swing.JButton();
        DeleteCollumnBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CollumnsTable = new javax.swing.JTable();
        AttTypeCombo = new javax.swing.JComboBox();
        addTypes();

        setModal(true);
        setResizable(false);
        setTitle("New Table Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 10.0;
        jPanel3.add(jButton1, gridBagConstraints);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weightx = 0.2;
        jPanel3.add(jButton2, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(NameText, gridBagConstraints);
        NameText.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setText("Comment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(CommentText, gridBagConstraints);

        jLabel8.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel8, gridBagConstraints);

        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HEAP", "BOB", "InnoDB" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(TypeCombo, gridBagConstraints);

        jLabel9.setText("Row Format");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel9, gridBagConstraints);

        RowFormatCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEFAULT", "DYNAMIC", "FIXED", "COMPRESSED" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(RowFormatCombo, gridBagConstraints);

        jLabel10.setText("Database");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel10, gridBagConstraints);

        DatabaseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseComboActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(DatabaseCombo, gridBagConstraints);

        jTabbedPane1.addTab("General", jPanel1);

        panel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Attribute Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        panel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Data Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(CollNameText, gridBagConstraints);

        jLabel5.setText("Length");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        panel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Default Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(jLabel6, gridBagConstraints);

        CollLengthText.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(CollLengthText, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 375;
        panel1.add(CollDefaultText, gridBagConstraints);

        jLabel7.setText("Extra Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel1.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 500;
        panel1.add(CollExtraValText, gridBagConstraints);

        PrimaryKeyCheck.setText("Primary Key");
        PrimaryKeyCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        PrimaryKeyCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        PrimaryKeyCheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrimaryKeyCheckStateChanged(evt);
            }
        });
        PrimaryKeyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimaryKeyCheckActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(PrimaryKeyCheck, gridBagConstraints);

        ForeignKeyCheck.setText("Foreign Key");
        ForeignKeyCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ForeignKeyCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ForeignKeyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeignKeyCheckActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(ForeignKeyCheck, gridBagConstraints);

        IndexCheck.setText("Index");
        IndexCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        IndexCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(IndexCheck, gridBagConstraints);

        CompulsoryCheck.setText("Compulsory");
        CompulsoryCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        CompulsoryCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(CompulsoryCheck, gridBagConstraints);

        Incrementcheck.setText("Auto Increment");
        Incrementcheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Incrementcheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(Incrementcheck, gridBagConstraints);

        zerofillcheck.setText("Zero Fill");
        zerofillcheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        zerofillcheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(zerofillcheck, gridBagConstraints);

        Signedcheck.setText("Unsigned");
        Signedcheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Signedcheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(Signedcheck, gridBagConstraints);

        addCollumnsBn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        addCollumnsBn.setText("++");
        addCollumnsBn.setNextFocusableComponent(CollNameText);
        addCollumnsBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCollumnsBnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(addCollumnsBn, gridBagConstraints);

        DeleteCollumnBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18));
        DeleteCollumnBtn.setText("--");
        DeleteCollumnBtn.setNextFocusableComponent(CollNameText);
        DeleteCollumnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCollumnBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel1.add(DeleteCollumnBtn, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 170));
        CollumnsTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        // this is the per initilaizjflksdfj cone
        // jai Shree RAm
        CollumnsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Data Types", "Key", "Mandatory", "Index", "Length", "Default", "Auto Increment", "Foreign Key", "Extra Value", "Unsigned", "Zero Fill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CollTableModel = (javax.swing.table.DefaultTableModel) CollumnsTable.getModel();
        CollumnsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        CollumnsTable.setDoubleBuffered(true);
        CollumnsTable.setDragEnabled(true);
        CollumnsTable.setEditingColumn(1);
        CollumnsTable.setEditingRow(1);
        jScrollPane1.setViewportView(CollumnsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        panel1.add(jScrollPane1, gridBagConstraints);

        AttTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttTypeComboActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        panel1.add(AttTypeCombo, gridBagConstraints);

        jTabbedPane1.addTab("Source", panel1);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.NORTH);
        jTabbedPane1.getAccessibleContext().setAccessibleName("General");

        add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        State = true; // the user successfully submitted the form to the system
        setVisible( false ); // make form invisible to user
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        State = false; // user cancelled the form
        setVisible( false );// make form invisible to user
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AttTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttTypeComboActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_AttTypeComboActionPerformed

    private void PrimaryKeyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimaryKeyCheckActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_PrimaryKeyCheckActionPerformed

    private void ForeignKeyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeignKeyCheckActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ForeignKeyCheckActionPerformed

    private void PrimaryKeyCheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrimaryKeyCheckStateChanged
// TODO add your handling code here:
        if ( PrimaryKeyCheck.isSelected() )
        {
            ForeignKeyCheck.setSelected( false  );
            CompulsoryCheck.setSelected( false  );
        }
        
    }//GEN-LAST:event_PrimaryKeyCheckStateChanged

    private void DatabaseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseComboActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_DatabaseComboActionPerformed

    private void DeleteCollumnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCollumnBtnActionPerformed
// TODO add your handling code here:
        try{
           
        if( CollumnsTable.getSelectedRowCount() > 0 )
        CollTableModel.removeRow( CollumnsTable.getSelectedRowCount() -1 );
        }
        catch( Exception e )
        {
            System.out.println( e );
        }
    }//GEN-LAST:event_DeleteCollumnBtnActionPerformed

    private void addCollumnsBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCollumnsBnActionPerformed
// TODO add your handling code here:
    Object[] array  = new Object[ 12 ];
    array[0] =  CollNameText.getText();
    array[1] =  ( String ) AttTypeCombo.getSelectedItem();
    array[2] = Boolean.toString( PrimaryKeyCheck.isSelected() ) ;
    array[3] = Boolean.toString( CompulsoryCheck.isSelected() ) ;
    array[4] = Boolean.toString( IndexCheck.isSelected() ) ;
    array[5] = CollLengthText.getText();
    array[6] = CollDefaultText.getText();
    array[9] = CollExtraValText.getText();
    array[10] = Boolean.toString( Signedcheck.isSelected() ) ;
    array[11] = Boolean.toString( zerofillcheck.isSelected() ) ;
    CollTableModel.insertRow(CollumnsTable.getSelectedRowCount() , array ); 
    
    // reset original values 
    this.resetKeyValues();
    
    // give selected focus
    CollNameText.requestFocus();
    }//GEN-LAST:event_addCollumnsBnActionPerformed
    
    
    protected void resetKeyValues()
    {
        
        CollNameText.setText( "" );
        CollLengthText.setText( "10" );
        CollDefaultText.setText( "" );
        PrimaryKeyCheck.setSelected( false );
        ForeignKeyCheck.setSelected( false );
        IndexCheck.setSelected( false );
        CompulsoryCheck.setSelected( false );
        Incrementcheck.setSelected( false );
        Signedcheck.setSelected( false );
        zerofillcheck.setSelected( false );
    }// func ends
    
    
    /*** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        
        // inform parent frame of user action ie. submit or cancel
        State = false; // user cancelled
    }//GEN-LAST:event_closeDialog
    
    /**
     * This is an imp code for displaying the form to the user. The main Frame is resposible for displaaying it. 
     */
    public boolean display()
    {
        
        setVisible( true );
        return State;// inform frame about user activity
        
    }// func ends 
   
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseTableChangeInterface getDatabaseTableCreatedInterface()
    {
        return  new createNewTableConverter();
    }// func ends
    
     public  String getDatabase()
    {
        return ( String ) DatabaseCombo.getSelectedItem();
    }
    
     
    public String getTableName()
    {
        return NameText.getText();
    }
    
    /***
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_New_Table(new java.awt.Frame(), null).setVisible(true);
            }
        });
    }
    
    
  /**
   *   Mutators
   */
    
    public void setDatabase( String DB )
    {
        DatabaseCombo.addItem( DB );
    }
    
  // private Vector Collumn;
   private javax.swing.table.DefaultTableModel CollTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AttTypeCombo;
    private javax.swing.JTextField CollDefaultText;
    private javax.swing.JTextField CollExtraValText;
    private javax.swing.JTextField CollLengthText;
    private javax.swing.JTextField CollNameText;
    private javax.swing.JTable CollumnsTable;
    protected javax.swing.JTextField CommentText;
    private javax.swing.JCheckBox CompulsoryCheck;
    protected javax.swing.JComboBox DatabaseCombo;
    private javax.swing.JButton DeleteCollumnBtn;
    private javax.swing.JCheckBox ForeignKeyCheck;
    private javax.swing.JCheckBox Incrementcheck;
    private javax.swing.JCheckBox IndexCheck;
    protected javax.swing.JTextField NameText;
    private javax.swing.JCheckBox PrimaryKeyCheck;
    private javax.swing.JComboBox RowFormatCombo;
    private javax.swing.JCheckBox Signedcheck;
    private javax.swing.JComboBox TypeCombo;
    private javax.swing.JButton addCollumnsBn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel1;
    private javax.swing.JCheckBox zerofillcheck;
    // End of variables declaration//GEN-END:variables
    
    // this stores if user filled the form or not
    private boolean State;
    // for getting the list of types supported by database
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.DatabaseReader DbRead = null;
    
    
    private class createNewTableConverter implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseTableChangeInterface 
    {
        public String returnChangedDatabase(){
            return ( String )DatabaseCombo.getItemAt( 0 );
        }// func ends
        
        public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table returnDatabaseAffectingTable()
        {
            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table Tb = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table();
           
            Tb.setName( getTableName() );
            
            Tb.setType( this.getTableType() );
            
            Tb.setComment( this.getCommentText() );
              
            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] Att = this.returnAttributes();
            
            for( int i=0; i< Att.length; i++ )
            {
                Tb.addAttribute( Att[i] );
            }
                        
            return Tb;
        }// func ends
        
        private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] returnAttributes(){
            
            String[] CollNm = this.returnCollumnNames();
            
            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] Att = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[ CollNm.length ];
                           
            for( int i=0; i< Att.length; i++ )
            {
             
                Att[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute( );    
        
                Att[i].setName( CollNm[i] ); 
                             
                Att[i].setType( this.returnCollType( CollNm[i] ));
                
                Att[i].setKey( this.getAttributeKey( CollNm[i]) );
                
                try{
                Att[i].setSize( Integer.parseInt( this.getAttributeLength ( CollNm[i] ) ) );
                }
                catch( Exception e )
                {
                    System.out.println( e );
                  
                }
                
            }
            
            
            return Att;
        }
        
         /***
     * This code is for getting the names of the attributes.
     */
    private String[] returnCollumnNames()
    {
        String [] Name= new String[ CollumnsTable.getRowCount() ];
     //   System.out.println( "\n\n");
        for( int i= 0; i< Name.length; i++ )
        {
            Name[ i ] =( String ) CollumnsTable.getValueAt( i, 0 );
          //  System.out.println( Name [i] );
        }
        
        return Name;
    }// func ends
    
    
    /**
     *This function does gets the type of the attribute of the table being passed as parameter.
     */
    /**
     * the implemetation here is simple. but must be remobed.
     */
    private String returnCollType( String AttName )
    {
        int i;
        for(  i= 0; i< CollumnsTable.getRowCount() ; i++ )
        {
          if( AttName.equals( ( String ) CollumnsTable.getValueAt( i, 0 ) ) )
          break;
        }
        return ( String ) CollumnsTable.getValueAt( i, 1 ); // return the type of the att name at i
    }// func ends
    
    
    /**
     *This function does gets the type of the attribute of the table being passed as parameter.
     */
    /**
     * the implemetation here is simple. but must be remobed.
     */
    private String getAttributeKey( String AttName )
    {
        int i;
        for(  i= 0; i< CollumnsTable.getRowCount() ; i++ )
        {
          if( AttName.equals( ( String ) CollumnsTable.getValueAt( i, 0 ) ) )
          break;
        }
        
        String state = ( String ) CollumnsTable.getValueAt( i, 2 ); // return the type of the att name at i
        
        return Boolean.parseBoolean(state)?org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute.PRIMARY_KEY:org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute.ORDINARY_KEY;
        
    }// func ends
    
    /**
     *this function returns the primary keys in the table.
     */
    private String[] returnPrimaryKeys()
    {
        java.util.ArrayList<String> Prim = new java.util.ArrayList<String>();
        try{             
        for(  int i= 0; i< CollumnsTable.getRowCount() ; i++ ){
         String temp =    ( String ) CollumnsTable.getValueAt( i, 2 );
         if( temp != null ){
           
        if( temp.equals( "true" ) )
        Prim.add((String) CollumnsTable.getValueAt( i, 0 ) );
        }
         
         else
         {
              System.out.println(  i+ " has a null value in temp" );
         }
        }
        
        //Object[] array;
        String[] retarray = new String[0];        
        retarray = Prim.toArray(retarray);
       // String[] retarray = new String[array.length];
        /**for( int i =0;i<array.length;i++)
            retarray[i] = (String)array[i];
        */
        return retarray;
        }
        catch( Exception e)
        {            
            System.out.println(  e );
            return null;
        }
        
    }// func ends 
    
    private String getAttributeLength( String AttName )
    {
        int i;
        for(  i= 0; i< CollumnsTable.getRowCount() ; i++ )
        {
          if( AttName.equals( ( String ) CollumnsTable.getValueAt( i, 0 ) ) )
          break;
        }
        return ( String ) CollumnsTable.getValueAt( i, 5 ); // return the type of the att name at i
    }// func ends
    
    
   
    
    
    private String getCommentText()
    {
          return CommentText.getText();
    }
    
    private String getTableType()
    {
        return ( String )TypeCombo.getSelectedItem();
    }
    
    }// converter class ends
    
    
    
}
