
//                          !! RAM !!

/**
 * DatabaseFindCmp.java
 *
 * Created on October 25, 2007, 1:09 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

/***
 *
 * @author  sumit
 */
public class DatabaseFindCmp extends javax.swing.JDialog {
    /*** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /*** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /*** Creates new form DatabaseFindCmp */
    public DatabaseFindCmp(java.awt.Frame parent ) {
        super(parent, true ); // modal
        initComponents();
        super.setLocationRelativeTo( null );
    }
    
    /*** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        TypeGroup = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InputWordText = new javax.swing.JTextField();
        IgnoreCaseCheck = new javax.swing.JCheckBox();
        TableBtn = new javax.swing.JRadioButton();
        DBbtn = new javax.swing.JRadioButton();
        viewbtn = new javax.swing.JRadioButton();
        Procbtn = new javax.swing.JRadioButton();

        setTitle("Database Find");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("FIND");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("FIND WHAT");

        InputWordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputWordTextActionPerformed(evt);
            }
        });

        IgnoreCaseCheck.setText("Ignore Case");
        IgnoreCaseCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        IgnoreCaseCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        TypeGroup.add(TableBtn);
        TableBtn.setText("Table");
        TableBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        TableBtn.setEnabled(false);
        TableBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));

        TypeGroup.add(DBbtn);
        DBbtn.setText("Database");
        DBbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        DBbtn.setEnabled(false);
        DBbtn.setMargin(new java.awt.Insets(0, 0, 0, 0));

        TypeGroup.add(viewbtn);
        viewbtn.setText("View");
        viewbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        viewbtn.setEnabled(false);
        viewbtn.setMargin(new java.awt.Insets(0, 0, 0, 0));

        TypeGroup.add(Procbtn);
        Procbtn.setText("Procedure");
        Procbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Procbtn.setEnabled(false);
        Procbtn.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputWordText, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IgnoreCaseCheck)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TableBtn)
                            .addComponent(viewbtn))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DBbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(cancelButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Procbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(okButton)
                    .addComponent(InputWordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IgnoreCaseCheck)
                    .addComponent(cancelButton)
                    .addComponent(TableBtn)
                    .addComponent(DBbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewbtn)
                    .addComponent(Procbtn))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputWordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputWordTextActionPerformed
        doClose( RET_OK );
    }//GEN-LAST:event_InputWordTextActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /*** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    public String getFindWord(){
        return this.InputWordText.getText();
    }
    
    public boolean isIgnoreCase(){
        return this.IgnoreCaseCheck.isSelected();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DBbtn;
    private javax.swing.JCheckBox IgnoreCaseCheck;
    private javax.swing.JTextField InputWordText;
    private javax.swing.JRadioButton Procbtn;
    private javax.swing.JRadioButton TableBtn;
    private javax.swing.ButtonGroup TypeGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton viewbtn;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
