
//                           !! RAM !!


/**
 * DocumentFindForm.java
 *
 * Created on October 26, 2007, 8:02 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

/***
 *
 * @author  sumit
 */
public class DocumentFindForm extends javax.swing.JDialog {
    /*** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /*** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /*** Creates new form DocumentFindForm */
    public DocumentFindForm(java.awt.Frame parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor Editor, javax.swing.JEditorPane EditPane ) {
        super(parent, true );
        this.Editor = Editor;
        this.EditPane = EditPane;
        initComponents();
        super.setLocationRelativeTo( null );
    }
    
    /*** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        FindBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        IgnoreCaseCheck = new javax.swing.JCheckBox();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Find Dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        FindBtn.setText("Find");
        FindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 19, 0, 0);
        getContentPane().add(FindBtn, gridBagConstraints);

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        getContentPane().add(CancelBtn, gridBagConstraints);

        jLabel1.setText("FIND WHAT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });
        Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InputKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(Input, gridBagConstraints);

        IgnoreCaseCheck.setText("Ignore Case");
        IgnoreCaseCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        IgnoreCaseCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(IgnoreCaseCheck, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputKeyPressed
 if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE ){
            this.doClose( 0 );
        }
    }//GEN-LAST:event_InputKeyPressed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        find();
    }//GEN-LAST:event_InputActionPerformed
    
    private void FindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBtnActionPerformed
        find();
    }//GEN-LAST:event_FindBtnActionPerformed

    private final void find() {
        String result = this.Editor.findText( Input.getText() );
        this.onFind( result );
    }
    
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_CancelBtnActionPerformed
    
    /*** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        this.Editor.initialize();
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    /**
     * code for reacting the finding
     */
    private void onFind( String Result ){
        
        if( Result == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor.NOT_FOUND ){
            Input.selectAll();
            Input.requestFocusInWindow();
            javax.swing.JOptionPane.showMessageDialog( null, Result,"Text Not Found", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
        else
            if( Result == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor.TEXT_NULL ){
            javax.swing.JOptionPane.showMessageDialog( null, Result,"Null Text", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
            else
                if( Result == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor.REACHED_LAST ){
                    javax.swing.JOptionPane.showMessageDialog( null, Result,"Reached Last", javax.swing.JOptionPane.INFORMATION_MESSAGE );
                }
                else
                    if( Result == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor.FOUND ){
                        int position = this.Editor.getPosition();
                        EditPane.select( -- position , position + Input.getText().length() );
                        // NOTE:: HERE I DECREMENT POSITION ACCOUNTING FOR THE ADDITOIN OF @ CHARACTER AT THE START OF BUFFER.
                    }
    }
    
   /***
   16-3-2007 8:25am
   this is the module for keeping track of input word changes.
   */
   public void addDocumentListener(){      
   
   Input.getDocument().addDocumentListener(
      new javax.swing.event.DocumentListener()
      {
        
        public void removeUpdate( javax.swing.event.DocumentEvent e)
        {
          Editor.initialize();
        }
        
        public void changedUpdate( javax.swing.event.DocumentEvent e)
        {          
          Editor.initialize();
        }
        
        public void insertUpdate( javax.swing.event.DocumentEvent e )
        {
           Editor.initialize();
        }
        
      }
    );
    
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton FindBtn;
    private javax.swing.JCheckBox IgnoreCaseCheck;
    private javax.swing.JTextField Input;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor Editor= null;
    private javax.swing.JEditorPane EditPane = null;
}
