
//                             !! RAM !!

/**
 * DocumentReplaceForm.java
 *
 * Created on October 27, 2007, 12:13 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

import java.awt.HeadlessException;

/***
 *
 * @author  sumit
 */
public class DocumentReplaceForm extends javax.swing.JDialog {
    
    /*** Creates new form DocumentReplaceForm */
    public DocumentReplaceForm(java.awt.Frame parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor Editor, javax.swing.JEditorPane EditPane) {
        super(parent, true );
        this.Editor = Editor;
        this.EditPane = EditPane;
        initComponents();
        this.addDocumentListener();
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JCheckBox jCheckBox1;
        javax.swing.JCheckBox jCheckBox2;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SourceText = new javax.swing.JTextField();
        DestinationText = new javax.swing.JTextField();
        ReplaceBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Replace");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Replace With");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        getContentPane().add(jLabel2, gridBagConstraints);

        SourceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SourceTextKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(SourceText, gridBagConstraints);

        DestinationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationTextActionPerformed(evt);
            }
        });
        DestinationText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DestinationTextKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        getContentPane().add(DestinationText, gridBagConstraints);

        ReplaceBtn.setText(this.Type ? "Replace All":"Replace");
        ReplaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplaceBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        getContentPane().add(ReplaceBtn, gridBagConstraints);

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(CancelBtn, gridBagConstraints);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ignore Case");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setEnabled(false);
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Highlight Result");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setEnabled(false);
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        getContentPane().add(jCheckBox2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DestinationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationTextActionPerformed
        find();
    }//GEN-LAST:event_DestinationTextActionPerformed

    private void ReplaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplaceBtnActionPerformed
        find();
    }//GEN-LAST:event_ReplaceBtnActionPerformed

    private void find() throws HeadlessException {
        if( this.Type ){
            this.Editor.replaceAll( this.SourceText.getText(), this.DestinationText.getText() );
        }
        else{
        final String State = this.Editor.replaceWord( this.SourceText.getText(), this.DestinationText.getText() );
        if( State == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor.REACHED_LAST ){
            javax.swing.JOptionPane.showMessageDialog( null, State+"\n so continuing from first again" ,"Replace Reached Last",javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }
    }

    private void DestinationTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DestinationTextKeyPressed
        if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE ){
            this.onClose();
        }
    }//GEN-LAST:event_DestinationTextKeyPressed

    private void SourceTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SourceTextKeyPressed
        if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE ){
            this.onClose();
        } 
    }//GEN-LAST:event_SourceTextKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.onClose();
    }//GEN-LAST:event_formWindowClosed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.onClose();
    }//GEN-LAST:event_CancelBtnActionPerformed
    
    public void onClose(){
        this.Editor.initialize();
        this.setVisible( false );
    }
    
   /***
   16-3-2007 8:25am
   this is the module for keeping track of input word changes.
   */
   public final void addDocumentListener(){      
   
   this.SourceText.getDocument().addDocumentListener(
      new javax.swing.event.DocumentListener()
      {
        
        public void removeUpdate( javax.swing.event.DocumentEvent e)
        {
          Editor.initialize();
        }
        
        public void changedUpdate( javax.swing.event.DocumentEvent e)
        {          
          Editor.initialize();
        }
        
        public void insertUpdate( javax.swing.event.DocumentEvent e )
        {
           Editor.initialize();
        }
        
      }
    );
    
    this.DestinationText.getDocument().addDocumentListener(
      new javax.swing.event.DocumentListener()
      {
        
        public void removeUpdate( javax.swing.event.DocumentEvent e)
        {
          Editor.initialize();
        }
        
        public void changedUpdate( javax.swing.event.DocumentEvent e)
        {          
          Editor.initialize();
        }
        
        public void insertUpdate( javax.swing.event.DocumentEvent e )
        {
           Editor.initialize();
        }
        
      }
    );
    
   }
    
   public void setReplaceType( final boolean Type ){
       this.Type = Type;
       this.ReplaceBtn.setText( Type? "Replace All":"Replace");
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField DestinationText;
    private javax.swing.JButton ReplaceBtn;
    private javax.swing.JTextField SourceText;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.DocumentEditor Editor= null;
    private javax.swing.JEditorPane EditPane = null;
    private boolean Type = this.REPLACE_ALL;
    
    
    public static final boolean REPLACE_SINGLE = false ;
    public static final boolean REPLACE_ALL = true ;
}
