
//                           !! RAM !!

/**
 * InsertTableCollForm.java
 *
 * Created on September 26, 2007, 10:16 AM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

import javax.swing.table.TableColumn;

/**
 *
 * @author  sumit
 */
public class InsertTableCollForm extends javax.swing.JDialog {
    
    /** Creates new form InsertTableCollForm */
    public InsertTableCollForm(java.awt.Frame parent, String Tb, String[] SuppTypesList  ) {
        super(parent, true );
        this.Types = SuppTypesList;
        initComponents();
        TableName = Tb;
        
        super.setLocationRelativeTo( null );                
    }

    private void addTypes( ) {
                
        if( this.Types != null){
            for( int i=0 ;i< Types.length; i++ ){
                this.AttTypeCombo.addItem( Types[i] );
            }            
        }
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CollNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CollLengthText = new javax.swing.JTextField();
        CollDefaultText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CollExtraValText = new javax.swing.JTextField();
        PrimaryKeyCheck = new javax.swing.JCheckBox();
        ForeignKeyCheck = new javax.swing.JCheckBox();
        IndexCheck = new javax.swing.JCheckBox();
        CompulsoryCheck = new javax.swing.JCheckBox();
        Incrementcheck = new javax.swing.JCheckBox();
        zerofillcheck = new javax.swing.JCheckBox();
        Signedcheck = new javax.swing.JCheckBox();
        AttTypeCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert Table Attributes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2)
                .addComponent(jButton1))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jLabel3.setText("Attribute Name");

        jLabel4.setText("Data Type");

        jLabel5.setText("Length");

        jLabel6.setText("Default Value");

        CollLengthText.setText("10");

        jLabel7.setText("Extra Value");

        PrimaryKeyCheck.setText("Primary Key");
        PrimaryKeyCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        PrimaryKeyCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        PrimaryKeyCheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrimaryKeyCheckStateChanged(evt);
            }
        });
        PrimaryKeyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimaryKeyCheckActionPerformed(evt);
            }
        });

        ForeignKeyCheck.setText("Foreign Key");
        ForeignKeyCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ForeignKeyCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ForeignKeyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeignKeyCheckActionPerformed(evt);
            }
        });

        IndexCheck.setText("Index");
        IndexCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        IndexCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        CompulsoryCheck.setText("Compulsory");
        CompulsoryCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        CompulsoryCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        Incrementcheck.setText("Auto Increment");
        Incrementcheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Incrementcheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        zerofillcheck.setText("Zero Fill");
        zerofillcheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        zerofillcheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        Signedcheck.setText("Unsigned");
        Signedcheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Signedcheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        addTypes();
        AttTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttTypeComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CollLengthText, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(zerofillcheck)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IndexCheck)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addComponent(CompulsoryCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Signedcheck)
                                            .addComponent(ForeignKeyCheck)
                                            .addComponent(Incrementcheck))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(PrimaryKeyCheck)))
                            .addGap(15, 15, 15))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CollExtraValText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CollDefaultText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AttTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CollNameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                            .addContainerGap()))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CollNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AttTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollLengthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CollDefaultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollExtraValText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimaryKeyCheck)
                    .addComponent(ForeignKeyCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Signedcheck)
                    .addComponent(CompulsoryCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndexCheck)
                    .addComponent(Incrementcheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zerofillcheck)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        State = false; // user cancelled the form
        setVisible( false );// make form invisible to user
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        State = true; // the user successfully submitted the form to the system
        setVisible( false ); // make form invisible to user
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AttTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttTypeComboActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_AttTypeComboActionPerformed

    private void ForeignKeyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeignKeyCheckActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ForeignKeyCheckActionPerformed

    private void PrimaryKeyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimaryKeyCheckActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_PrimaryKeyCheckActionPerformed

    private void PrimaryKeyCheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrimaryKeyCheckStateChanged
// TODO add your handling code here:
        if ( PrimaryKeyCheck.isSelected() ) {
            ForeignKeyCheck.setSelected( false  );
            CompulsoryCheck.setSelected( false  );
        }
    }//GEN-LAST:event_PrimaryKeyCheckStateChanged
    
    /**
     * This is an imp code for displaying the form to the user. The main Frame is resposible for displaaying it. 
     */
    public boolean display(){        
        setVisible( true );
        return State;// inform frame about user activity        
    }// func ends
    
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeChangedInterface getTableCollChangeEvent(){
        return Con;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AttTypeCombo;
    private javax.swing.JTextField CollDefaultText;
    private javax.swing.JTextField CollExtraValText;
    private javax.swing.JTextField CollLengthText;
    private javax.swing.JTextField CollNameText;
    private javax.swing.JCheckBox CompulsoryCheck;
    private javax.swing.JCheckBox ForeignKeyCheck;
    private javax.swing.JCheckBox Incrementcheck;
    private javax.swing.JCheckBox IndexCheck;
    private javax.swing.JCheckBox PrimaryKeyCheck;
    private javax.swing.JCheckBox Signedcheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel1;
    private javax.swing.JCheckBox zerofillcheck;
    // End of variables declaration//GEN-END:variables
    
     private javax.swing.table.DefaultTableModel CollTableModel;
     private boolean State = false;
     
     private String[] Types = null;
     
     private org.edu.gces.s2005.projects.frontendformysql.ui.Forms.InsertTableCollForm.InsertFormCollForm_Converter Con = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.InsertTableCollForm.InsertFormCollForm_Converter();
     
     private String TableName = null;
     
     
     
     
     /**
      *  here is the covertor class that will be a inner component for coverting this UI info into domain info.
      */
     public class InsertFormCollForm_Converter implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeChangedInterface {
       
       private final String getTableName()
       {
           return TableName;
       }// func ends
       
       public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] getChangedAttributes()
       {
           return null; // no use for more info see interface
       }// func   ends
       
       public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table getChangedTable()
       {
           org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table Tb = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table();
           
           Tb.setName( this.getTableName() );
           
           return Tb;
           
       }// func ends
       
       public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] getNewAttributesValues(){        
               try{
               org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute temp = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute();
               
               temp.setName( CollNameText.getText() );
               
               temp.setKey(PrimaryKeyCheck.isSelected()? org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute.PRIMARY_KEY: org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute.ORDINARY_KEY);
               
               try{
               temp.setSize(Integer.parseInt( CollLengthText.getText() ) );
               }
               catch( Exception e )
               {
                   System.out.println( " problem in size parsing" + e );
                   return null;
               }
               
               temp.setType(( String ) AttTypeCombo.getSelectedItem());
               
               try{
               temp.setNullable( CompulsoryCheck.isSelected() );
               }
               catch( Exception e)
               {
                   System.out.println( "problem in nullable parsing"+e );
                   return null;
               }
               
               temp.setDefaultValue(CollDefaultText.getText());
               
               org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] AddAtt = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[ 1 ];
           
               AddAtt[0] = temp;
           
               return AddAtt;
               }
               catch( Exception e ){
                   System.out.println("Exception while adding Attribute " + e.getMessage() );
                   return null;
               }               
       }// func ends
       
     }// class ends
     
     }

