
//                      !! RAM !!

/**
 * InsertValuesInTable.java
 *
 * Created on August 28, 2007, 7:11 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

/***
 *
 * @author  sumit
 */
public class InsertValuesInTable extends javax.swing.JDialog {
    
    /*** Creates new form InsertValuesInTable */
    public InsertValuesInTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        InputTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TableValueInsertForm");
        setMinimumSize(null);
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 100));
        InputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "User Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InputTableModel = ( javax.swing.table.DefaultTableModel ) InputTable.getModel();
        jScrollPane1.setViewportView(InputTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 44;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 65, 0, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
         this.OnCancellingSubmit();
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        this.OnCancellingSubmit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        this.OnSubmit();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setTypes( String[] V )
    {
        if( V.length < 0)
            return ;
        
        // else
        for( int i=0; i<V.length; i++ )
        {
        Object[] Row= new Object[2]; 
        Row[0] =  V[i];
        Row[1] = ""; // empty String
        InputTableModel.addRow( Row );
        }
        
    }
    
    public boolean setVisible()
    {
        this.setVisible( true );
        
        return SubmitState;
    } // func ends
    
    public void OnSubmit()
    {
        SubmitState = true;
        setVisible( false );
    }// func ends
    
    public void OnCancellingSubmit()
    {
        this.setVisible( false );
    }// func ends
    
    public Object[] returnValuesInserted()
    {
        Object[] ValueInsert = new String[ InputTable.getRowCount() ];
             System.out.print( InputTable.getRowCount()+" " );
        for( int i=0 ;i<ValueInsert.length; i++)
        {                 
                 /**
                  * here is a problem.
                  *when the last coll of the imputtable is in focus and we have ot read value then it doesnt give its valueproperly
                  */
            ValueInsert[i] = (String)InputTableModel.getValueAt( i, 1 );
            System.out.print( (String)((java.util.Vector)InputTableModel.getDataVector().elementAt( i )).elementAt( 1 ) + "||");
        }
        
        return ValueInsert;
    } // func ends
    
    /***
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertValuesInTable(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InputTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    // back end data
    private boolean SubmitState = false;
    private javax.swing.table.DefaultTableModel InputTableModel = null;
}
