
//                             !! RAM !!

/**
 * NewForm.java
 *
 * Created on October 25, 2007, 5:50 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Forms;

/***
 *
 * @author  sumit
 */
public class NewForm extends javax.swing.JDialog {
    
    /*** Creates new form NewForm */
    public NewForm( org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame p ) {
        super(p, true);
        this.parent = p;
        initComponents();
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CreateGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Dbbtn = new javax.swing.JRadioButton();
        TbBtn = new javax.swing.JRadioButton();
        ViewBtn = new javax.swing.JRadioButton();
        ProcBtn = new javax.swing.JRadioButton();
        TrigBtn = new javax.swing.JRadioButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New");
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel1.setText("Create New");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        CreateGroup.add(Dbbtn);
        Dbbtn.setText("Database");
        Dbbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Dbbtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(Dbbtn, gridBagConstraints);

        CreateGroup.add(TbBtn);
        TbBtn.setText("Table");
        TbBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        TbBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(TbBtn, gridBagConstraints);

        CreateGroup.add(ViewBtn);
        ViewBtn.setText("View");
        ViewBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ViewBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(ViewBtn, gridBagConstraints);

        CreateGroup.add(ProcBtn);
        ProcBtn.setText("Procedure");
        ProcBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ProcBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(ProcBtn, gridBagConstraints);

        CreateGroup.add(TrigBtn);
        TrigBtn.setText("Trigger");
        TrigBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        TrigBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(TrigBtn, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible( false );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Create();
        setVisible( false );
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void Create(){
        System.out.println( "the selected button is " + CreateGroup.getSelection().getActionCommand() );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CreateGroup;
    private javax.swing.JRadioButton Dbbtn;
    private javax.swing.JRadioButton ProcBtn;
    private javax.swing.JRadioButton TbBtn;
    private javax.swing.JRadioButton TrigBtn;
    private javax.swing.JRadioButton ViewBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame parent = null;
}
