
//                                   !! RAM !!

/**
 * DatabaseServerPanel.java
 *
 * Created on February 10, 2008, 2:48 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard;

/***
 *
 * @author Sumit Shrestha
 */
public class DatabaseServerPanel extends javax.swing.JPanel implements org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.WizardInterface{
    
    /*** Creates new form DatabaseServerPanel */
    public DatabaseServerPanel( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        this.Engine = Engine;
        initComponents();
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DbServerNm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PtNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DbURL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Database Server Info");

        jLabel2.setText("Database Server Name");

        jLabel3.setText("like mysql, oracle, etc");

        jLabel4.setText("Port No");

        PtNo.setEditable(false);
        PtNo.setFocusable(false);

        jLabel5.setText("like  3306");

        jLabel6.setText("Database URL");

        jLabel7.setText("like  jdbc:mysql://localhost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DbServerNm, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DbURL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(PtNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DbServerNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(PtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DbURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean onNext(){
        String DbServerNm = this.DbServerNm.getText();
        String DbServerURL = this.DbURL.getText();
        
        String DriverID = this.Engine.getRecentlyAddedDriver();
        
        if( this.isValid(DbServerNm, DbServerURL ) ){
            
            String mess = this.Engine.renameDriverServerName(DriverID, DbServerNm );
            
            if( mess != org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.SuccessfullModification ){
                javax.swing.JOptionPane.showMessageDialog( this, mess, "Error while setting Driver Server Name", javax.swing.JOptionPane.ERROR_MESSAGE );            
                return false;
            }          
            
            mess = this.Engine.renameDriverServerURL( DriverID, DbServerURL);
            if( mess != org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.SuccessfullModification ){
                javax.swing.JOptionPane.showMessageDialog( this, mess, "Error while setting Driver Server URL", javax.swing.JOptionPane.ERROR_MESSAGE );            
                return false;
            }
            
            return true;            
        }
        else{
            javax.swing.JOptionPane.showMessageDialog( this, "Invalid Database Server Name or URL or Port No", "Error in Input", javax.swing.JOptionPane.ERROR_MESSAGE );            
            return false;
        }
    }
    
    private boolean isValid( String DbSrvName, String DbSrvURL ){
        return ! ( DbSrvURL.equals( "" ) || DbSrvName.equals( "" ) );
    }
    
    public boolean onBack(){
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DbServerNm;
    private javax.swing.JTextField DbURL;
    private javax.swing.JTextField PtNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
}
