
//                                   !! RAM !!

/**
 * DriverPanel.java
 *
 * Created on February 10, 2008, 2:33 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard;

/**
 *
 * @author  Sumit Shrestha
 */
public class DriverPanel extends javax.swing.JPanel implements org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.WizardInterface{
    
    /** Creates new form DriverPanel */
    public DriverPanel( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        this.Engine = Engine;
        initComponents();
        this.DriverName.setText( "com.mysql.cj.jdbc.Driver" );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DriverName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DriverHTTP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DriverFile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Driver Info");

        jLabel2.setText("Driver Name:");

        jLabel3.setText("Driver Location");

        jLabel4.setText("like          com.mysql.cj.jdbc.Driver");

        jLabel5.setText("http://");

        DriverHTTP.setEditable(false);
        DriverHTTP.setFocusable(false);

        jLabel6.setText("like          http://www.mysql.com/drivers/mysql-connector1.5.jar");

        jLabel7.setText("file://");

        jLabel8.setText("like          file://localhost/C:/mysql-connector-java-5.0.6-bin.jar");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(DriverFile, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DriverHTTP, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                            .addComponent(DriverName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(DriverHTTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1)
                    .addComponent(DriverFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.io.File path = this.FileBrowser.showOpenDialog();
        
        if( path != null && path.getAbsolutePath() != null )
            this.DriverFile.setText( path.getAbsolutePath() );
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean isValidURL(){
        return !( this.DriverFile.equals("") );
    }
    
    private final String processJarURL( ){
        try{        
        
        String DrFile = this.DriverFile.getText();
        
        if( ! this.isValidURL() ){
            javax.swing.JOptionPane.showMessageDialog( this, "File fields are both empty.", "Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            return null;
        }
        
        /**if( ! ( tempURL.startsWith("http://") || tempURL.startsWith( "file://" )) ){
            String Prefix = isFile ? "file:///" : "http://" ;
            tempURL = Prefix + tempURL;
        } */          
        //tempURL = tempURL.replace( '\\','/');// if it used windows separator then change it
                
        return DrFile;
        }
        catch( Exception e ){
            javax.swing.JOptionPane.showMessageDialog( this, e.getMessage(), "Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            return null;
        }
    }
    
    public boolean onNext(){
        try{
        String DrNm = this.DriverName.getText();
        
        
        if( DrNm .equals("")){
            javax.swing.JOptionPane.showMessageDialog( this, "Invalid name", "Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            return false;
        }
        
        final String DrPath = this.processJarURL();
        
        if( DrPath == null )
            return false;
        
        String Mess = this.Engine.addDriver( DrNm, DrPath );
        
        if( Mess != org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.SuccessfullDriverAddition )
            javax.swing.JOptionPane.showMessageDialog( this, Mess, "Error!! ", javax.swing.JOptionPane.ERROR_MESSAGE );
        
        return Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.SuccessfullDriverAddition;
        }
        catch( Exception e ){
            javax.swing.JOptionPane.showMessageDialog( this, e.getMessage(), "Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            return false;
        }
        
    }
    
    public boolean onBack(){
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DriverFile;
    private javax.swing.JTextField DriverHTTP;
    private javax.swing.JTextField DriverName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.File.FileChooser FileBrowser = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.File.FileChooser( "jar" );
}
