
//                                !! RAM !!

/**
 * NewDriverWizard.java
 *
 * Created on February 10, 2008, 2:20 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard;

/***
 *
 * @author  Sumit Shrestha
 */
public class NewDriverWizard extends javax.swing.JDialog {
    
    /*** Creates new form NewDriverWizard */
    public NewDriverWizard(java.awt.Dialog parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        super( parent, true );
        initComponents();
        
        this.PanelArray[0] = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.WelcomePage();
        this.PanelArray[1] = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.DriverPanel( Engine );
        this.PanelArray[2] = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.DatabaseServerPanel( Engine );
        this.PanelArray[3] =  new org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.CompletionPanel() ;
       
        this.addComponentstoCentralPanel();      
        this.setLocationRelativeTo( null );
    }
    
    /**
     * This method will add the panels to central panel
     */
    public void addComponentstoCentralPanel(){
              
       for( int i = 0; i< 4; i++)
       this.CentralPanel.add( ( java.awt.Component ) this.PanelArray[i] );
       
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CentralPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Driver Wizard");
        setMinimumSize(new java.awt.Dimension(400, 350));
        setModal(true);
        setResizable(false);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        CentralPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(CentralPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.CardLayout card = ( java.awt.CardLayout )( this.CentralPanel.getLayout() );        
        
        if( ! this.PanelArray[ this.presentlyVisiblePanel ].onNext() )
            return;
        
        if( this.Next() )// it is not last
            card.next( this.CentralPanel );        
        else
            this.setVisible( false ); // after last exit
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.CardLayout card = ( java.awt.CardLayout )( this.CentralPanel.getLayout() );        
        
        if( ! this.PanelArray[ this.presentlyVisiblePanel ].onBack() )
            return ;
        
        if( this.Back() )
            card.previous( this.CentralPanel );
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean Next(){
        if( this.presentlyVisiblePanel == 3 )
            return false;
        
        this.presentlyVisiblePanel ++;
        return true;
    }
    
    public boolean Back(){
        if( this.presentlyVisiblePanel == 0 )
            return false;
        
        this.presentlyVisiblePanel --;
        return true;
    }
    
    /***
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewDriverWizard dialog = new NewDriverWizard(new java.awt.Dialog( new javax.swing.JFrame() ), null );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
            
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CentralPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    // field to keep track of presently visible panel
    private int presentlyVisiblePanel = 0;
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.WizardInterface[] PanelArray = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.WizardInterface[4];
}
