
//                            !! RAM !!

/**
 * DatabaseTree.java
 *
 * Created on October 24, 2007, 2:51 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.parent;

import java.awt.HeadlessException;

/**
 * This Class represents the Database tree in UI form. It works in conjucation with the main frame. The class was created with the vision of separating the main frame that initially hold all the UI tasks.
 * 
 * @author  sumit
 */
public class DatabaseTree extends javax.swing.JPanel {
    
    /** Creates new form DatabaseTree */
    public DatabaseTree( org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame p, org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd eng  ) {
        this.ParentFrame = p;
        this.Engine = eng;
        initComponents();
        this.jScrollPane1 = new javax.swing.JScrollPane( this.DBTree );
        this.add( this.jScrollPane1 );
    }

    private void deleteSelectedTable() throws HeadlessException, HeadlessException {
        if (this.isSelectedNodeDatabase()) {
            deleteDatabase();
        } else if (this.isSelectedNodeTable()) {
            if (javax.swing.JOptionPane.showConfirmDialog(null, "Are You Sure You want to delete the Selected Table", "Table Deletion Confirmation", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE) == javax.swing.JOptionPane.OK_OPTION) {
                this.deleteTableusingTree();
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableMenu = new javax.swing.JPopupMenu();
        Open = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        TableDataAdd = new javax.swing.JMenuItem();
        TableCollAdd = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        deleteTable = new javax.swing.JMenuItem();
        DatabaseNodeMenu = new javax.swing.JPopupMenu();
        expandThisNode1 = new javax.swing.JMenuItem();
        add = new javax.swing.JMenuItem();
        DatabaseMenu = new javax.swing.JPopupMenu();
        expandThisNode2 = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator7 = new javax.swing.JSeparator();
        delete = new javax.swing.JMenuItem();
        ViewNodeMenu = new javax.swing.JPopupMenu();
        expandThisNode3 = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator6 = new javax.swing.JSeparator();
        addView = new javax.swing.JMenuItem();
        ViewMenu = new javax.swing.JPopupMenu();
        openView = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator8 = new javax.swing.JSeparator();
        DeletethisView = new javax.swing.JMenuItem();
        TableNodeMenu = new javax.swing.JPopupMenu();
        expandThisNode = new javax.swing.JMenuItem();
        javax.swing.JSeparator jSeparator5 = new javax.swing.JSeparator();
        addTable = new javax.swing.JMenuItem();
        DBTree = new javax.swing.JTree();
        DBTree.setVisible( false );
        DBTreeModel =  (javax.swing.tree.DefaultTreeModel ) DBTree.getModel();
        RootNode = new javax.swing.tree.DefaultMutableTreeNode(org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree.DATABASE );
        DBTreeModel.setRoot( RootNode );

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        TableMenu.add(Open);
        TableMenu.add(jSeparator2);

        TableDataAdd.setText("addData");
        TableDataAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableDataAddActionPerformed(evt);
            }
        });
        TableMenu.add(TableDataAdd);

        TableCollAdd.setText("addColumn");
        TableCollAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableCollAddActionPerformed(evt);
            }
        });
        TableMenu.add(TableCollAdd);
        TableMenu.add(jSeparator1);

        deleteTable.setText("DeleteTable");
        deleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTableActionPerformed(evt);
            }
        });
        TableMenu.add(deleteTable);

        expandThisNode1.setText("expandNode");
        expandThisNode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandThisNode1ActionPerformed(evt);
            }
        });
        DatabaseNodeMenu.add(expandThisNode1);

        add.setText("add\n");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        DatabaseNodeMenu.add(add);

        expandThisNode2.setText("expandNode");
        expandThisNode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandThisNode2ActionPerformed(evt);
            }
        });
        DatabaseMenu.add(expandThisNode2);
        DatabaseMenu.add(jSeparator7);

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        DatabaseMenu.add(delete);

        expandThisNode3.setText("expandNode");
        expandThisNode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandThisNode3ActionPerformed(evt);
            }
        });
        ViewNodeMenu.add(expandThisNode3);
        ViewNodeMenu.add(jSeparator6);

        addView.setText("add");
        addView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addViewActionPerformed(evt);
            }
        });
        ViewNodeMenu.add(addView);

        openView.setText("open");
        openView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openViewActionPerformed(evt);
            }
        });
        ViewMenu.add(openView);
        ViewMenu.add(jSeparator8);

        DeletethisView.setText("delete");
        DeletethisView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletethisViewActionPerformed(evt);
            }
        });
        ViewMenu.add(DeletethisView);

        expandThisNode.setText("expandNode");
        expandThisNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandThisNodeActionPerformed(evt);
            }
        });
        TableNodeMenu.add(expandThisNode);
        TableNodeMenu.add(jSeparator5);

        addTable.setText("add");
        addTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableActionPerformed(evt);
            }
        });
        TableNodeMenu.add(addTable);

        DBTree.setDragEnabled(true);
        DBTree.setEditable(true);
        DBTree.setFocusTraversalPolicyProvider(true);
        DBTree.setOpaque(false);
        DBTree.setShowsRootHandles(true);
        DBTree.setToggleClickCount(0);
        DBTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DBTreeMouseClicked(evt);
            }
        });
        DBTree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DBTreeKeyPressed(evt);
            }
        });

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void addTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableActionPerformed
        this.TableNodeMenu.setVisible( false );
        
        try{
        this.Engine.selectDatabase( this.getSelectednode().getParent().toString() );        
        }
        catch( Exception e ){
            System.out.println( "excepiton "+ e.getMessage() );
        }
        
        this.ParentFrame.createTable();
    }//GEN-LAST:event_addTableActionPerformed

    private void expandThisNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandThisNodeActionPerformed
        this.disablePopupMenus();
        this.DBTree.expandPath( this.DBTree.getSelectionPath());
    }//GEN-LAST:event_expandThisNodeActionPerformed

    private void DeletethisViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletethisViewActionPerformed
        this.ViewMenu.setVisible( false );
        this.deleteView();
    }//GEN-LAST:event_DeletethisViewActionPerformed

    private void openViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openViewActionPerformed
        this.ViewMenu.setVisible( false );
        this.ParentFrame.displayTable( this.getSelectednode() );
    }//GEN-LAST:event_openViewActionPerformed

    private void addViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addViewActionPerformed
        this.ViewNodeMenu.setVisible( false );
        this.ParentFrame.createView();
    }//GEN-LAST:event_addViewActionPerformed

    private void expandThisNode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandThisNode3ActionPerformed
        this.DBTree.expandPath( this.DBTree.getSelectionPath());
        this.disablePopupMenus();
    }//GEN-LAST:event_expandThisNode3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        this.DatabaseMenu.setVisible( false );
        this.deleteDatabase( );
    }//GEN-LAST:event_deleteActionPerformed

    private void expandThisNode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandThisNode2ActionPerformed
        this.disablePopupMenus();
        this.DBTree.expandPath( this.DBTree.getSelectionPath());
    }//GEN-LAST:event_expandThisNode2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        this.DatabaseNodeMenu.setVisible( false );
        this.ParentFrame.addDatabase();
    }//GEN-LAST:event_addActionPerformed

    private void expandThisNode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandThisNode1ActionPerformed
        this.disablePopupMenus();
        this.DBTree.expandPath( this.DBTree.getSelectionPath());
    }//GEN-LAST:event_expandThisNode1ActionPerformed

    private void TableCollAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableCollAddActionPerformed
        this.TableMenu.setVisible( false );
        this.ParentFrame.displayTable( this.getSelectednode() ).addTableColumn();
    }//GEN-LAST:event_TableCollAddActionPerformed

    private void TableDataAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableDataAddActionPerformed
        this.TableMenu.setVisible( false );
        this.ParentFrame.displayTable( this.getSelectednode() ).addTableData();
    }//GEN-LAST:event_TableDataAddActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        this.TableMenu.setVisible( false );
        this.ParentFrame.displayTable( this.getSelectednode() );
    }//GEN-LAST:event_OpenActionPerformed

    private void DBTreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DBTreeKeyPressed
        if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE ){
            deleteSelectedTable();
        }
    }//GEN-LAST:event_DBTreeKeyPressed

    private final boolean isMenuClick( java.awt.event.MouseEvent evt ){
        return evt.getButton() == evt.BUTTON3;
    }
    
    private final boolean isSingleClick( java.awt.event.MouseEvent evt ){
        return evt.getButton() == evt.BUTTON1 && evt.getClickCount() == 2;
    }
    
    private void DBTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DBTreeMouseClicked
        this.disablePopupMenus();
        try{                   
        javax.swing.tree.TreePath SelectedPath = this.DBTree.getClosestPathForLocation( evt.getX(), evt.getY());
        if( SelectedPath == null ){
            return;
        }
        if( this.DBTree.getPathBounds(SelectedPath).contains( evt.getX(), evt.getY()) ){                
            javax.swing.tree.TreeNode ClickedNode = (javax.swing.tree.TreeNode) SelectedPath.getLastPathComponent();
            this.DBTree.setSelectionPath(SelectedPath);
            System.out.println( "This is the selected node " + ClickedNode.toString() );
        }
        else
            return;
        
        if( this.isMenuClick( evt )){
                
                if( this.getSelectednode() == this.RootNode  ) 
                    this.displayPopupMenu( evt, DatabaseNodeMenu );
                
                else
                    if( this.isSelectedNodeDatabase() )                        
                        displayPopupMenu(evt, this.DatabaseMenu );
                    
                    else
                        if (  this.getSelectednode().getParent().toString() == this.TABLE )
                            this.displayPopupMenu( evt, TableMenu );
                        
                        else
                            if( this.getSelectednode().toString() == this.VIEW )
                                this.displayPopupMenu( evt, ViewNodeMenu );
                            
                            else
                                if( this.getSelectednode().getParent().toString() == this.VIEW )
                                    this.displayPopupMenu( evt, ViewMenu );
                                
                                else
                                    if( this.getSelectednode().toString() == this.TABLE )
                                        this.displayPopupMenu( evt, TableNodeMenu );
            } 
            else
                if( this.isSingleClick( evt )){
                    if (  this.getSelectednode().getParent().toString() == this.TABLE ){
                        this.TableMenu.setVisible( false );
                        this.ParentFrame.displayTable( this.getSelectednode() );
                    }
                    else
                        if( this.getSelectednode().getParent().toString() == this.VIEW ){
                            this.ParentFrame.displayTable( this.getSelectednode() );
                        }                    
                                    else
                                        if( this.getSelectednode().getParent().toString() == this.PROCEDURE ){ // for any procedure node click                                           
                                            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ProcedureInterface Proc = null;
                                            Proc = this.Engine.getDatabaseReader().readProcedure( this.getSelectednode().toString(), this.Engine.returnSelectedDatabase() );
                                            if( Proc != null ){
                                                org.edu.gces.s2005.projects.frontendformysql.ui.parent.ProcedureBuilderPanel p = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.ProcedureBuilderPanel( Proc, this.Engine, this.Engine.returnSelectedDatabase() );
                                                this.ParentFrame.displayComponet( p, "Procedure::"+ Proc.getName()  );
                                            } 
                                        }
            
                }                 
        } catch( Exception e) {
        }
    }//GEN-LAST:event_DBTreeMouseClicked

    private void deleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTableActionPerformed
        this.deleteSelectedTable();
}//GEN-LAST:event_deleteTableActionPerformed

    private void displayPopupMenu(final java.awt.event.MouseEvent evt, final javax.swing.JPopupMenu Menu ) {
        /**
         Menu.setLocation( this.getX() + evt.getX(), this.getY() + evt.getY() );
        Menu.setVisible(true );
         */
        Menu.show(evt.getComponent(),evt.getX(), evt.getY());
    }
    
    
    /**
     *
     * called when the user wants to disable the popup menu once enabled.
     */
    private final void disablePopupMenus() {
        if ( this.DatabaseMenu.isVisible() )
        {
            this.DatabaseMenu.setVisible(false );
        }
        else
            if ( this.DatabaseNodeMenu.isVisible() )
        {
            this.DatabaseNodeMenu.setVisible( false );
        }
            else
                if( this.TableMenu.isVisible() ){
                    this.TableMenu.setVisible( true );
                }
                else
                    if( this.ViewNodeMenu.isVisible() )
                        this.ViewNodeMenu.setVisible( false );
                    else
                        if( this.ViewMenu.isVisible() )
                            this.ViewMenu.setVisible( false );
                        else
                            if( this.TableNodeMenu.isVisible() )
                                this.TableNodeMenu.setVisible( false );
    }

    
    private final void deleteDatabase() throws java.awt.HeadlessException {
        if( javax.swing.JOptionPane.showConfirmDialog( null, "Are You Sure You want to delete the Selected Database", "Database Deletion Confirmation",javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE ) == javax.swing.JOptionPane.OK_OPTION )
            if( this.ParentFrame.DbOperator.deleteDatabase( this.getSelectednode().toString() ) )
            this.removeDatabase( this.getSelectednode() );
    }
        
    private final boolean isSelectedNodeTable( )
    {   
        try{
        return org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree.TABLE.equalsIgnoreCase ( this.getSelectednode().getParent().toString() );    
        }
        catch( Exception e )
        {
            return false;
        }
    }    
    

    private final boolean isSelectedNodeDatabase( )
    {
        return this.getSelectednode().getParent() == RootNode;
    }// func ends
    
    private final javax.swing.tree.DefaultMutableTreeNode getSelectednode()
    {       
        return (javax.swing.tree.DefaultMutableTreeNode) DBTree.getLastSelectedPathComponent();
    }
    
    
    final void addViewtoDBtree(final String ViewName) {
        javax.swing.tree.DefaultMutableTreeNode AddViewNode = getViewNode();
        this.DBTreeModel.insertNodeInto( new javax.swing.tree.DefaultMutableTreeNode( ViewName ), AddViewNode, 0 );
    }// func ends

    
    private final javax.swing.tree.DefaultMutableTreeNode getViewNode() {
        javax.swing.tree.DefaultMutableTreeNode AddViewNode = (javax.swing.tree.DefaultMutableTreeNode) this.returnChild( this.RootNode , Engine.returnSelectedDatabase() ).getChildAt( 1 );
        return AddViewNode;
    }
    
      
   public javax.swing.tree.DefaultMutableTreeNode returnChild( javax.swing.tree.DefaultMutableTreeNode Parent , String Child )
   {
       for( int i=0;i<Parent.getChildCount(); i++)
       {
           javax.swing.tree.DefaultMutableTreeNode node = ( javax.swing.tree.DefaultMutableTreeNode ) Parent.getChildAt( i );
           if( node.toString().equals( Child ) )
           {
               return node;
           }
       }
       // else if Child dosent exists
       return null;
   }
  
   void addTableToDatabaseTree(final String TbName, final String Db  ) {
        javax.swing.tree.DefaultMutableTreeNode NewTable = new javax.swing.tree.DefaultMutableTreeNode( TbName );
        javax.swing.tree.DefaultMutableTreeNode db = this.returnChild( RootNode, Db );
        if( db != null ) {
            //( (javax.swing.tree.DefaultMutableTreeNode)db.getChildAt(0) ).add( NewTable );
            DBTreeModel .insertNodeInto( NewTable , (javax.swing.tree.DefaultMutableTreeNode) db.getChildAt(0) , db.getChildAt(0).getChildCount());
            
            //Make sure the user can see the lovely new node.
            
            DBTree.scrollPathToVisible(new javax.swing.tree.TreePath( NewTable.getPath()) );
            
        } else {
            // report error that databases doesnt exists
            System.out.println("databases doesnt exists");
        }
    }
   
      final void initialize(){
        if( this.jScrollPane1.getComponentCount() == 0 ) // if database is reconnected after disconnecting then,
        {
            this.jScrollPane1.add( this.DBTree );
            this.jScrollPane1.repaint();
            this.jScrollPane1.setVisible( false );
        }
      }
      
      final void display(){
          DBTree.setVisible( true ); 
      }
      
      final void empty(){
        this.jScrollPane1.removeAll();
          
        while( this.RootNode.getChildCount() > 0 )
            this.DBTreeModel.removeNodeFromParent( ( javax.swing.tree.DefaultMutableTreeNode ) this.RootNode.getFirstChild() );
        
        this.jScrollPane1.repaint();
        
      }
      
      
    final void addNewDatabase( String Db ) 
    {
        try{
        
            javax.swing.tree.DefaultMutableTreeNode DBNode = new javax.swing.tree.DefaultMutableTreeNode( Db );       
            
            DBNode.add( new javax.swing.tree.DefaultMutableTreeNode( this.TABLE ) );
            DBNode.add( new javax.swing.tree.DefaultMutableTreeNode( this.VIEW ) );            
            
            this.fillDatabase( DBNode);
            this.addProcedure( DBNode );
            
            this.DBTreeModel.insertNodeInto( DBNode, this.RootNode, 0 );
        }
        catch( Exception e)
        {
            System.out.println( e +" in addnewdb" );
        }
    }// func ends
    
    
    
    private final void addProcedure( javax.swing.tree.DefaultMutableTreeNode DBNode ){
        String[]  list = this.Engine.getDatabaseReader().getProcedureList( DBNode.toString() );
        javax.swing.tree.DefaultMutableTreeNode ProcNode = new javax.swing.tree.DefaultMutableTreeNode( this.PROCEDURE );
        
        if( list != null ){
        for( int i=0 ; i< list.length; i++){
            javax.swing.tree.DefaultMutableTreeNode addproc = new javax.swing.tree.DefaultMutableTreeNode( list[i] );
            ProcNode.add( addproc );
        }
        }
        
        DBNode.add( ProcNode );
    }// func ends
    
    
    final void removeDatabase( javax.swing.tree.DefaultMutableTreeNode DBNode )
    {
        this.DBTreeModel.removeNodeFromParent( DBNode );
    }// func ends
   
     
   public final void fillDatabase( javax.swing.tree.DefaultMutableTreeNode DbNd){
       try{
      
       String[] array = this.Engine.getDatabaseReader().returnTableList( DbNd.toString() );
       
       if( array == null )
           return;
       
       for( int i=0; i< array.length; i++){         
                 for( int j=0; j<DbNd.getChildCount(); j++){                 
                        this.DBTreeModel.insertNodeInto( (javax.swing.tree.MutableTreeNode) new javax.swing.tree.DefaultMutableTreeNode( array[i] ) ,(javax.swing.tree.MutableTreeNode)DbNd.getChildAt(j) , 0 );                 
                 }
       }       
       }
       catch( Exception e)
       {
           System.out.println( e + " exception in filling table node 4 database " + DbNd.toString() );
       }
   }
    
   
   public final void setDatabase() 
   {
       try{
       this.RootNode = new javax.swing.tree.DefaultMutableTreeNode( this.DATABASE ) ;
       this.DBTreeModel.setRoot( this.RootNode );
       
       this.setCatalogs();
       
       // finally after adding thin`gs display 
       this.jScrollPane1.setVisible( true );
       
       }
       catch( Exception e)
       {
           System.out.println( e );
       }
   }// func ends
   
   public final void setCatalogs( )
   {
       try{
       String[] DbList = this.Engine.getDatabaseReader().readDatabaseList();

       if( DbList == null )
           return;
       
       for( int i = 0;i< DbList.length ;i++ )
       {
           this.addNewDatabase( DbList[ i ]  );
       }
       
       }
       catch( Exception e )
       {
           System.out.println( "exception while setting catalog "+ e);
       }
   }// func ends
  
   final void deleteView()
   {
       if( ! ( javax.swing.JOptionPane.showConfirmDialog( null, "Are You sure you want to delete the selected View?" , "View Deletion Confirmation",javax.swing.JOptionPane.WARNING_MESSAGE ) == javax.swing.JOptionPane.YES_OPTION ) )
            return;
       
       String Mess = null;       
       
       org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseViewChangeInterface deletedView = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseViewChangeInterface(){
           
           public String getDatabaseName(){
               return getSelectednode().getParent().getParent().toString();
           }
           
           public String getViewName(){
               return getSelectednode().toString();
           }
           
           public String getScript(){
               return null;
           }
       };
       
       if( ( Mess = Engine.deleteView( deletedView )) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS  )
       {
           this.DBTreeModel.removeNodeFromParent( this.returnChild( this.getViewNode(), deletedView.getViewName() ) );
           javax.swing.JOptionPane.showMessageDialog( null, "View was deleted successfully" , "View Delete Success!!", javax.swing.JOptionPane.INFORMATION_MESSAGE );
       }
       else
       {
           javax.swing.JOptionPane.showMessageDialog( null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ),  "View Delete Failure!!", javax.swing.JOptionPane.ERROR_MESSAGE );
       }
       
   }// func ends
   
   
   void deleteTableusingTree( )
   {
       org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseTableChangeInterface DelTbEvnt = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DatabaseTableChangeInterface ()
       {             
      public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table returnDatabaseAffectingTable(){
          
          if( isSelectedNodeTable( ) ){
      org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table DelTb = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table();
      
      DelTb.setName( getSelectednode().toString() );
      return DelTb;
          }
          return null;
      }
      
      
      public String returnChangedDatabase(){
          if ( isSelectedNodeTable( ) )
              return getSelectednode().getParent().getParent().toString();
          // else
          return null;
      }    
       }; // interface defn ends
       
       String Mess = null;
       
       if(( Mess = Engine.deleteTable( DelTbEvnt ) ) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS )
       {
           // upate UI           
           if( this.ParentFrame.isAlreadyOpenedinTab( getSelectednode().getParent().getParent().toString()  + "/"+ getSelectednode().toString() ) )
               this.ParentFrame.removeTab( getSelectednode().getParent().getParent().toString()  + "/"+ getSelectednode().toString()  );           
           DBTreeModel.removeNodeFromParent( getSelectednode() );           
            // report user
           javax.swing.JOptionPane.showMessageDialog( null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ), "Table Deletion Success !!", javax.swing.JOptionPane.INFORMATION_MESSAGE );
       }
       else
       {
           // report user
           javax.swing.JOptionPane.showMessageDialog( null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ), "Table Deletion Failure !!", javax.swing.JOptionPane.ERROR_MESSAGE );
       }
       
   }// func ends

   public org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree.SearchComponent getTreeSearcher(){
       return this.EditCmp;
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree DBTree;
    private javax.swing.JPopupMenu DatabaseMenu;
    private javax.swing.JPopupMenu DatabaseNodeMenu;
    private javax.swing.JMenuItem DeletethisView;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem TableCollAdd;
    private javax.swing.JMenuItem TableDataAdd;
    private javax.swing.JPopupMenu TableMenu;
    private javax.swing.JPopupMenu TableNodeMenu;
    private javax.swing.JPopupMenu ViewMenu;
    private javax.swing.JPopupMenu ViewNodeMenu;
    private javax.swing.JMenuItem add;
    private javax.swing.JMenuItem addTable;
    private javax.swing.JMenuItem addView;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem deleteTable;
    private javax.swing.JMenuItem expandThisNode;
    private javax.swing.JMenuItem expandThisNode1;
    private javax.swing.JMenuItem expandThisNode2;
    private javax.swing.JMenuItem expandThisNode3;
    private javax.swing.JMenuItem openView;
    // End of variables declaration//GEN-END:variables
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
    private javax.swing.tree.DefaultTreeModel DBTreeModel = null;
    private javax.swing.tree.DefaultMutableTreeNode RootNode;
    private javax.swing.JScrollPane jScrollPane1 = null;
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame ParentFrame= null;
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree.SearchComponent EditCmp = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree.SearchComponent();
    // some constants
    public  final static String TABLE = "TABLE";
    public final static String VIEW = "VIEW";
    public final static String PROCEDURE = "PROCEDURE";
    public final static String DATABASE = "DATABASE";
    
    /**
     *  THIS IS THE INNER CLASS OF THE DATABASE EDITOR FOR FIND AND REPLACE TASKS.
     */
        public class SearchComponent implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.TreeSearcher.TreeSearchInterface{
            
            public void find(){
                
                this.FindForm.setVisible( true );
                int state = this.FindForm.getReturnStatus();
                
                if( state == this.FindForm.RET_CANCEL )
                    return;
                
                // else
                findword = this.FindForm.getFindWord();
                
                this.TreeSearcher.setFindCond( findword, this.FindForm.isIgnoreCase() );
                
                if( findword == null ||  findword.equals("") )
                    return;
                // else
                this.TreeSearcher.recursive_find( RootNode );
            }
            
            
        public void displayNode(final javax.swing.tree.TreeNode Node) {
            javax.swing.tree.TreePath path = new javax.swing.tree.TreePath( ( (javax.swing.tree.DefaultMutableTreeNode) Node ).getPath());
            DBTree.scrollPathToVisible( path );                    
            DBTree.setSelectionPath( path );
        }
        
        public boolean continueSearch(){
            int choice = javax.swing.JOptionPane.showConfirmDialog( null, "Do you want to continue finding?","Continue?" ,javax.swing.JOptionPane.YES_NO_OPTION );
            if( choice != javax.swing.JOptionPane.OK_OPTION )
                return false;
            else
                return true;
        }
            private String findword = null;
            private org.edu.gces.s2005.projects.frontendformysql.ui.Forms.DatabaseFindCmp FindForm = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.DatabaseFindCmp( null ) ;
            private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.TreeSearcher TreeSearcher = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.Editor.TreeSearcher( this );
        }
    
}
