
//                                    !! RAM !!

/**
 * DriverManager.java
 *
 * Created on February 10, 2008, 9:40 AM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.parent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author  Sumit Shrestha
 */
public class DriverManagerDialog extends javax.swing.JDialog implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.DriverListener {

    private static final Logger LOG = LoggerFactory.getLogger(DriverManagerDialog.class);
    
    /*** Creates new form DriverManager */
    public DriverManagerDialog(java.awt.Frame parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        super(parent, false );
        this.Engine = Engine;
        initComponents();
        this.initializeDiverList();
        this.Engine.registerDriverListener( this );
        this.setLocationRelativeTo( null );
    }
    
    private void initializeDiverList(){
        this.DriverList.setModel( this.DriverListModel );        
        org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver[] Drivers = this.Engine.getLoadedDrivers();
        if( Drivers != null ){
            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver Default = this.Engine.getDefaultDriver();
            
            for( int i=0 ;i< Drivers.length; i++ ){
                this.onDriverAddition( Drivers[ i ] );
            }
            
            if( Default != null ){
                int index = Integer.parseInt( Default.getDriverID() );
                org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel DefaultDriverPanel = ( ( org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel ) this.CentralPanel.getComponent(index) );
                DefaultDriverPanel.setDefault( true );
            }
        }
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriverList = new javax.swing.JList();
        CentralPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        EditCheck = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Driver Manager Interface");
        setResizable(false);

        DriverList.setFont(new java.awt.Font("Tahoma", 1, 12));
        DriverList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DriverList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                DriverListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DriverList);

        sp.setLeftComponent(jScrollPane1);

        CentralPanel.setLayout(new java.awt.CardLayout());
        sp.setRightComponent(CentralPanel);

        jToolBar1.setRollover(true);

        jButton1.setText("ADD");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("REMOVE");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        jMenuItem1.setText("New Driver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        EditCheck.setText("Editable");
        EditCheck.setEnabled(false);
        EditCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EditCheckItemStateChanged(evt);
            }
        });
        jMenu2.add(EditCheck);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.addDriver();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.addDriver();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void EditCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EditCheckItemStateChanged
        if( evt.getStateChange() == evt.DESELECTED )
            return;
        try{
        ( (org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel)this.CentralPanel.getComponent( this.DriverList.getSelectedIndex() ) ).makeEditable();
        }
        catch( Exception e ){
            // do nothing
        }
}//GEN-LAST:event_EditCheckItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = this.DriverList.getSelectedIndex();
        
        if( index == -1 ){
            javax.swing.JOptionPane.showMessageDialog( this, "Please select the driver to delete from list.", "Driver Not selected", javax.swing.JOptionPane.ERROR_MESSAGE );
            return;
        }
        
        int result = javax.swing.JOptionPane.showConfirmDialog( this, "Are You sure you wanna delete this Driver?", "Driver Removal Confirmation", javax.swing.JOptionPane.YES_NO_OPTION );
        
        if( result != javax.swing.JOptionPane.OK_OPTION ){
            return;
        }
        
        final String mess = this.Engine.removeDriver( String.valueOf( index ) );
        
        if( mess != org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.SuccessfullDeletion )
            javax.swing.JOptionPane.showMessageDialog( this, mess, "Driver Deletion Error", javax.swing.JOptionPane.ERROR_MESSAGE );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible( false );
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void DriverListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_DriverListValueChanged
        if( evt.getValueIsAdjusting() ){
            return;            
        }
        int i = DriverList.getSelectedIndex();
        this.displayDriverInfoAt(i); 
    }//GEN-LAST:event_DriverListValueChanged
    
    private void displayDriverInfoAt( int index ){
        if( index < 0 )
            return;
        
        ( (java.awt.CardLayout)CentralPanel.getLayout() ).first( CentralPanel );
        for( int i=0; i< index;i++){
            ( (java.awt.CardLayout)CentralPanel.getLayout() ).next( CentralPanel );
        }
    }
    
    public void addDriver(){
        org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.NewDriverWizard Wizard = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.NewDriverWizard.NewDriverWizard( this, Engine );
        Wizard.setVisible( true );
    }// func ends   
    
    /**
     * This method will giver the driver panel of the driver name being supplied.
     * 
     * @param DriverName name of driver whose panel is to be obtained 
     * @returns panel object corressponding to drivername being sent if exists else null
     */
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel getDriverPanel( String DriverID ){
        if( DriverID == null )
            return null;
        
        return (org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel)this.CentralPanel.getComponent( Integer.parseInt(DriverID) );
    }              
    
    
    ///////////////////////// LISTENER CODE STARTS /////////////////////////////////////////////////////////
    public void onDriverLosd(){        
    }
    
    public void onDefaultDriverChanged( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver NewDefaultDriver, org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver OldDefaultDriver ){        
        try{         
     //       System.out.println( "main culprit:: this is old "+  OldDefaultDriver.getDriverName() );
                if( OldDefaultDriver != null ){
            org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel RemovedDefaultDriverPanel = this.getDriverPanel( OldDefaultDriver.getDriverID() );
            RemovedDefaultDriverPanel.setDefault( false );
                }
        }
        catch( Exception e ){
            LOG.error( "Error while switching default driver UI state", e );
        }
    }
    
    public void onDriverAddition( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver addedDriver ){
        this.DriverListModel.addElement( addedDriver.getDriverName() );       
        org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel NewDriver = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel( this.Engine );
        NewDriver.setDriverInfo(addedDriver);
        this.CentralPanel.add( addedDriver.getDriverName(),NewDriver );
        this.sp.resetToPreferredSizes();
        this.EditCheck.setEnabled( true );
    }    
    
    public void onDriverServerNameRename( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver renamedDriver ){
        org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel temp = this.getDriverPanel( renamedDriver.getDriverID() );
        temp.setDriverServerName( renamedDriver.getDatabaseServerName());
    }
    
    public void onDriverServerURLRename( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver renamedDriver ){
        org.edu.gces.s2005.projects.frontendformysql.ui.Components.DriverInfoPanel temp = this.getDriverPanel( renamedDriver.getDriverID() );
        temp.setDriverServerURL( renamedDriver.getDatabaseServerURL());
    }
    
    public void onDriverDelete( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver DeletedDriver ){
        for( int i=0;i< this.DriverList.getModel().getSize(); i++ )
            if( this.DriverList.getModel().getElementAt(i).equals( DeletedDriver.getDriverName() )){                
                this.DriverListModel.remove(i);
                this.CentralPanel.remove(i);
            }
    }
    
    ///////////////////////// LISTENER CODE ENDS /////////////////////////////////////////////////////////
    
    
    /***
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DriverManagerDialog dialog = new DriverManagerDialog(new javax.swing.JFrame(),null );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CentralPanel;
    private javax.swing.JList DriverList;
    private javax.swing.JCheckBoxMenuItem EditCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSplitPane sp;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
    private javax.swing.DefaultListModel DriverListModel = new javax.swing.DefaultListModel();
}
