
//                               !! RAM !!

/**
 * MainFrame.java
 *
 * Created on July 21, 2007, 2:53 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.parent;

import java.awt.HeadlessException;

import org.edu.gces.s2005.projects.frontendformysql.ui.Forms.Create_New_Table;

/**
 * This is the parent frame containing the entire software.
 * @author  sumit
 */
public class MainFrame extends javax.swing.JFrame {
    
    /** Creates new form MainFrame */
    public MainFrame( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        this.Engine = Engine;
        this.DbTree = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree( this, this.Engine );
        initComponents();
        this.addStatusBar();
        this.Enabler.onDisconnection();
        this.DriverMan = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.DriverManagerDialog( this, this.Engine );
        super.setLocationRelativeTo( null );        
    }
    
    private void addStatusBar(){
        this.getContentPane().add( this.StBar, java.awt.BorderLayout.SOUTH );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        javax.swing.JSplitPane jSplitPane2 = new javax.swing.JSplitPane();
        javax.swing.JTabbedPane MenuTab = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar3 = new javax.swing.JToolBar();
        jPanel9 = new javax.swing.JPanel();
        NewBtn = new javax.swing.JButton();
        OpenBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        SaveAsBtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar4 = new javax.swing.JToolBar();
        jPanel18 = new javax.swing.JPanel();
        CutBtn = new javax.swing.JButton();
        Copy = new javax.swing.JButton();
        PasteBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        ReplaceBtn = new javax.swing.JButton();
        ReplaceAllBtn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        FindBtn = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        SelectAllBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel19 = new javax.swing.JPanel();
        UndoBtn = new javax.swing.JButton();
        RedoBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar5 = new javax.swing.JToolBar();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar23 = new javax.swing.JToolBar();
        jPanel15 = new javax.swing.JPanel();
        CreateNewDatabaseBtn = new javax.swing.JButton();
        CreateNewTableBtn = new javax.swing.JButton();
        CreateViewBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CreateConstraintsBtn = new javax.swing.JButton();
        CreateTriggerBtn = new javax.swing.JButton();
        CreateProcBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar2 = new javax.swing.JToolBar();
        jPanel11 = new javax.swing.JPanel();
        CommitBtn1 = new javax.swing.JButton();
        RollBackBtn1 = new javax.swing.JButton();
        TransactionStateBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        ConnectBtn = new javax.swing.JButton();
        DisconnectBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar6 = new javax.swing.JToolBar();
        javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar7 = new javax.swing.JToolBar();
        TerminalBtn = new javax.swing.JButton();
        HistoryBtn = new javax.swing.JButton();
        SQLEditorBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        javax.swing.JPanel jPanel8 = new javax.swing.JPanel();
        javax.swing.JToolBar jToolBar8 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JPanel CentralPanel = new javax.swing.JPanel();
        CentralTab = new javax.swing.JTabbedPane();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database FrontEnd - A Complete Database Tool for DBA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "File", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        NewBtn.setText("New");
        NewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBtnActionPerformed(evt);
            }
        });
        jPanel9.add(NewBtn);

        OpenBtn.setText("Open");
        OpenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBtnActionPerformed(evt);
            }
        });
        jPanel9.add(OpenBtn);

        jToolBar3.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Backup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        SaveBtn.setText("Save");
        jPanel10.add(SaveBtn);

        SaveAsBtn.setText("Save As");
        SaveAsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsBtnActionPerformed(evt);
            }
        });
        jPanel10.add(SaveAsBtn);

        jToolBar3.add(jPanel10);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Exit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel13.add(ExitBtn);

        jToolBar3.add(jPanel13);

        jPanel1.add(jToolBar3, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("File", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel18.setOpaque(false);
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        CutBtn.setText("Cut");

        jPanel18.add(CutBtn);

        Copy.setText("Copy");
        jPanel18.add(Copy);

        PasteBtn.setText("Paste");
        jPanel18.add(PasteBtn);

        DeleteBtn.setText("Delete");
        jPanel18.add(DeleteBtn);

        jToolBar4.add(jPanel18);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Replace", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel17.setOpaque(false);
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        ReplaceBtn.setText("Replace");
        jPanel17.add(ReplaceBtn);

        ReplaceAllBtn.setText("Replace All");
        jPanel17.add(ReplaceAllBtn);

        jToolBar4.add(jPanel17);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Find", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel14.setOpaque(false);
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        FindBtn.setText("Find");
        jPanel14.add(FindBtn);

        jToolBar4.add(jPanel14);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        SelectAllBtn.setText("Select All");
        jPanel16.add(SelectAllBtn);

        jToolBar4.add(jPanel16);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Recovery", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        UndoBtn.setText("Undo");
        jPanel19.add(UndoBtn);

        RedoBtn.setText("Redo");
        jPanel19.add(RedoBtn);

        jToolBar4.add(jPanel19);

        jPanel2.add(jToolBar4, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("Edit", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jToolBar5, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("View", jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar23.setFocusable(false);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Create New", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel15.setOpaque(false);
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        CreateNewDatabaseBtn.setText("Database");
        CreateNewDatabaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewDatabaseBtnActionPerformed(evt);
            }
        });
        jPanel15.add(CreateNewDatabaseBtn);

        CreateNewTableBtn.setText("Table");
        CreateNewTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewTableBtnActionPerformed(evt);
            }
        });
        jPanel15.add(CreateNewTableBtn);

        CreateViewBtn.setText(" View");
        CreateViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateViewBtnActionPerformed(evt);
            }
        });
        jPanel15.add(CreateViewBtn);

        jButton6.setText("Function");
        jButton6.setEnabled(false);
        jPanel15.add(jButton6);

        CreateConstraintsBtn.setText("Constraints");
        CreateConstraintsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateConstraintsBtnActionPerformed(evt);
            }
        });
        jPanel15.add(CreateConstraintsBtn);

        CreateTriggerBtn.setText("Trigger");
        jPanel15.add(CreateTriggerBtn);

        CreateProcBtn.setText("Procedure");
        CreateProcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProcBtnActionPerformed(evt);
            }
        });
        jPanel15.add(CreateProcBtn);

        jToolBar23.add(jPanel15);

        jPanel4.add(jToolBar23);

        MenuTab.addTab("Create", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Transaction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        CommitBtn1.setText("Commit");
        CommitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommitBtn1ActionPerformed(evt);
            }
        });
        jPanel11.add(CommitBtn1);

        RollBackBtn1.setText("RollBack");
        RollBackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollBackBtn1ActionPerformed(evt);
            }
        });
        jPanel11.add(RollBackBtn1);

        TransactionStateBtn.setText("State");
        TransactionStateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionStateBtnActionPerformed(evt);
            }
        });
        jPanel11.add(TransactionStateBtn);

        jToolBar2.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Connection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospac821 BT", 0, 8), new java.awt.Color(0, 0, 0)));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        ConnectBtn.setMnemonic('V');
        ConnectBtn.setText("Connect");
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnActionPerformed(evt);
            }
        });
        jPanel12.add(ConnectBtn);

        DisconnectBtn.setText("Disconnect");
        DisconnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectBtnActionPerformed(evt);
            }
        });
        jPanel12.add(DisconnectBtn);

        jToolBar2.add(jPanel12);

        jPanel5.add(jToolBar2, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("Database", jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jToolBar6, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("Projects", jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        TerminalBtn.setText("SQL Terminal");
        TerminalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminalBtnActionPerformed(evt);
            }
        });
        jToolBar7.add(TerminalBtn);

        HistoryBtn.setText("History Window");
        HistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryBtnActionPerformed(evt);
            }
        });
        jToolBar7.add(HistoryBtn);

        SQLEditorBtn.setText("SQL Editor");
        SQLEditorBtn.setFocusable(false);
        SQLEditorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SQLEditorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SQLEditorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQLEditorBtnActionPerformed(evt);
            }
        });
        jToolBar7.add(SQLEditorBtn);

        jButton1.setText("Driver Management");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar7.add(jButton1);

        jPanel7.add(jToolBar7, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("Window", jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton2.setText("About");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar8.add(jButton2);

        jPanel8.add(jToolBar8, java.awt.BorderLayout.CENTER);

        MenuTab.addTab("Help", jPanel8);

        jSplitPane2.setLeftComponent(MenuTab);

        jSplitPane1.setLeftComponent( this.DbTree );

        /**
        * Here is the code for adding mnemonic of menu tabs after being added in above lines.
        * it has been added here due to the fact that all tabs must be first added.
        */

        MenuTab.setMnemonicAt( 0 , java.awt.event.KeyEvent.VK_F );
        MenuTab.setMnemonicAt( 1 , java.awt.event.KeyEvent.VK_E );
        MenuTab.setMnemonicAt( 2 , java.awt.event.KeyEvent.VK_V );
        MenuTab.setMnemonicAt( 3 , java.awt.event.KeyEvent.VK_C );
        MenuTab.setMnemonicAt( 4 , java.awt.event.KeyEvent.VK_D );
        MenuTab.setMnemonicAt( 5 , java.awt.event.KeyEvent.VK_P );
        MenuTab.setMnemonicAt( 6 , java.awt.event.KeyEvent.VK_W );
        MenuTab.setMnemonicAt( 7 , java.awt.event.KeyEvent.VK_H );

        /**
        * added code ends
        */

        CentralPanel.setLayout(new java.awt.BorderLayout());

        CentralTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        CentralTab.setAutoscrolls(true);
        CentralTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CentralTabStateChanged(evt);
            }
        });
        CentralPanel.add(CentralTab, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(CentralPanel);

        jSplitPane2.setRightComponent(jSplitPane1);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransactionStateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionStateBtnActionPerformed
        this.StBar.setStatus( "gathering the state of transaction..." );
        org.edu.gces.s2005.projects.frontendformysql.ui.Components.TransactionStateViewer View = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.TransactionStateViewer( this, this.Engine.getTransactionManager() );
        View.setVisible( true );
        this.StBar.setStatus( "state shown..." );
    }//GEN-LAST:event_TransactionStateBtnActionPerformed

    private void HistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryBtnActionPerformed
        this.TransacHistoryWindow.setVisible( true );
    }//GEN-LAST:event_HistoryBtnActionPerformed

    private void TerminalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminalBtnActionPerformed
        org.edu.gces.s2005.projects.frontendformysql.ui.parent.SQLTerminal Terminal = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.SQLTerminal( this.Engine );
        this.displayComponet( Terminal, "SQL Terminal");
    }//GEN-LAST:event_TerminalBtnActionPerformed

    private void SQLEditorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQLEditorBtnActionPerformed
        org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorPanel EditorPanel = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorPanel( this.Engine );
        this.displayComponet( EditorPanel, "SQL Editor");
    }//GEN-LAST:event_SQLEditorBtnActionPerformed

    private void SaveAsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsBtnActionPerformed
        try{            
            org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface SelectedEditor = (org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface ) this.CentralTab.getSelectedComponent();            
            SelectedEditor.getManager().save();
        }
        catch( java.lang.ClassCastException e ){
            // do nothing
        }
        catch( Exception e ){
            // do nothing
        }
    }//GEN-LAST:event_SaveAsBtnActionPerformed

    private void OpenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBtnActionPerformed
        try{            
            org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface SelectedEditor = (org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface ) this.CentralTab.getSelectedComponent();
            this.StBar.setStatus( "displying the open form..." );
            SelectedEditor.getManager().open();
            this.StBar.setStatus( "form displayed..." );
        }
        catch( java.lang.ClassCastException e ){
            // do nothing
        }
        catch( Exception e ){
            // do nothing
        }
    }//GEN-LAST:event_OpenBtnActionPerformed

    private void CreateConstraintsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateConstraintsBtnActionPerformed
        
    }//GEN-LAST:event_CreateConstraintsBtnActionPerformed

    private void NewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBtnActionPerformed
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.NewForm form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.NewForm( this );
        form.setVisible( true );
    }//GEN-LAST:event_NewBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        this.onExit();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        onExit();
    }//GEN-LAST:event_formWindowClosed

    private void onExit() {
        this.Engine.close();
        super.setVisible( false );
        super.dispose();
        System.exit( 0 );
    }

    private void CentralTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CentralTabStateChanged
        // this try block is for settings of the table        
        try{
            org.edu.gces.s2005.projects.frontendformysql.ui.parent.TablePanel p = ( org.edu.gces.s2005.projects.frontendformysql.ui.parent.TablePanel ) this.CentralTab.getSelectedComponent();
                try{                    
                    this.Engine.selectDatabase( p.getDatabaseName() );
                    this.Enabler.whenNotEditing();
                    this.StBar.setStatus( "woring on table..." );
                }
                catch( Exception e ){
                    // report
                    this.StBar.setStatus( "cannot set database..." );
                }
            }
        catch( java.lang.ClassCastException e ){
            boolean state = this.setEditActions();
            
            if( state ){// check if editing is being done                
                // enable file buttons 
                // enabling edit is not need since it is automatically done when adding action 
                this.Enabler.whenEditing();
                this.StBar.setStatus( "editing being done..." );
            }
            else{
                // means it is neither editing nor table like terminal or any future components that will be added.
                // so disable editing things
                this.Enabler.whenNotEditing();                
            }
        }
    }//GEN-LAST:event_CentralTabStateChanged

    private void CreateProcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProcBtnActionPerformed
        createProc();
    }//GEN-LAST:event_CreateProcBtnActionPerformed

    public void createProc() {
        this.StBar.setStatus( "cteating form..." );
        org.edu.gces.s2005.projects.frontendformysql.ui.parent.ProcedureBuilderPanel NewProc = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.ProcedureBuilderPanel( this.Engine, this.Engine.returnSelectedDatabase() );        
        this.StBar.setStatus( "displyaing form..." );
        this.displayComponet( NewProc , "Procedure Builder" ) ;
        this.StBar.setStatus( "form displayed..." );
    }

    private void CreateViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateViewBtnActionPerformed
        createView();
    }//GEN-LAST:event_CreateViewBtnActionPerformed

    public final void createView() throws HeadlessException {
        
        this.StBar.setStatus( "creating form..." );
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.createNewViewForm Form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.createNewViewForm( this, true );
        this.StBar.setStatus( "displaying form..." );
        if( Form.display() ){
            this.StBar.setStatus( "form submitted and processing form..." );
            String Mess = null;
            if( ( Mess = Engine.createView( Form ) ) ==  org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){                
                this.StBar.setStatus( "view created and displaying it..." );
                String ViewName = Form.getViewName();
                this.DbTree.addViewtoDBtree(ViewName);
                javax.swing.JOptionPane.showMessageDialog( this, "Congratulations!! \n\tView "+ ViewName + " was created" , "View Creation Success", javax.swing.JOptionPane.INFORMATION_MESSAGE );
            }
            else{
                this.StBar.setStatus( "error..." );
                javax.swing.JOptionPane.showMessageDialog( this, Mess, "View Creation Failure!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        }
        else
        {
            // do nothing
            this.StBar.setStatus( "form cancelled..." );
        }
    }


    private void RollBackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollBackBtn1ActionPerformed
        this.StBar.setStatus("Rolling back...");
        if( this.Engine.getTransactionManager().rollback() )
        this.StBar.setStatus("Rolled back");
        else
            this.StBar.setStatus( "Roll back Failed" );
    }//GEN-LAST:event_RollBackBtn1ActionPerformed

    private void CreateNewDatabaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewDatabaseBtnActionPerformed
        addDatabase();
    }//GEN-LAST:event_CreateNewDatabaseBtnActionPerformed

    private void CreateNewTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewTableBtnActionPerformed
        createTable();
    }//GEN-LAST:event_CreateNewTableBtnActionPerformed

    public void createTable() throws HeadlessException {
        
        this.StBar.setStatus( "creating form..." );
        Create_New_Table q = new Create_New_Table( this, this.Engine.getDatabaseReader()  );
        q.setDatabase( Engine.returnSelectedDatabase() );
        if ( q.display() ) {
            this.StBar.setStatus( "form shown..." );
            String Mess =  Engine.execute( q.getDatabaseTableCreatedInterface() );
            if( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
                this.DbTree.addTableToDatabaseTree( q.getTableName(), q.getDatabase() );
                this.StBar.setStatus( "table created..." );
            } else {
                // report the user
                this.StBar.setStatus( "error..." );
                javax.swing.JOptionPane.showMessageDialog(null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ),"Table Creation Error!!",javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        } else {
            // do nothing
            this.StBar.setStatus( "form cancelled..." );
        }
    }

        

    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBtnActionPerformed
        
        this.DbTree.initialize();
        
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.UserDataInputDialog Ip = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.UserDataInputDialog( this, true );// make it modal
        if ( ! Ip.setVisible() ){
            return;
        }
        // else
        this.StBar.setStatus("Connecting...");
        final String mess =  Engine.connect( Ip.getUser(),Ip.getPassword() );
        if ( mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.SuccessfullConnection ) {
            try{            
            this.DbTree.setDatabase( );            
            this.Enabler.onConnection();
            this.StBar.setStatus("Connected");
            
            // setting transaction manager to window 
            this.TransacHistoryWindow.setTransactionManager( this.Engine.getTransactionManager() );
            
            //finally display the tree
            this.DbTree.display();
            }
            catch( Exception e)
            {
                System.out.println( e );
            }
            
        } else {
            this.StBar.setStatus("Connection failed");
            javax.swing.JOptionPane.showMessageDialog( this , mess, "Database Connection Failure!! ", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
        
    }//GEN-LAST:event_ConnectBtnActionPerformed

    
    
    private void DisconnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectBtnActionPerformed
// TODO add your handling code here:
        this.StBar.setStatus("Disconnecting...");
        // reinitailize tree to point into new
        
        this.DbTree.empty();
        
        CentralTab.removeAll();       
        
        // disconnect
        Engine.close();
        
        this.Enabler.onDisconnection();
        
        this.StBar.setStatus("Disconnected");
    }//GEN-LAST:event_DisconnectBtnActionPerformed

    private void CommitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommitBtn1ActionPerformed
        this.StBar.setStatus("Commiting...");
        if( this.Engine.getTransactionManager().commit() )
        this.StBar.setStatus("Commited");
        else
            this.StBar.setStatus( "Commit Failed" );
    }//GEN-LAST:event_CommitBtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.DriverMan.setVisible( true );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Abt.setVisible( true );
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void addDatabase() {
        this.StBar.setStatus("Displying Form...");
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.createNewDatabaseForm Form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.createNewDatabaseForm( this, true );
        if( Form.display() ){            
            this.StBar.setStatus("Creating Database...");
            if( this.DbOperator.createDatabase( Form.getDbName() ) )
            {
                this.DbTree.addNewDatabase( Form.getDbName() );
                this.StBar.setStatus("Database Created");
            }
            else{
                this.StBar.setStatus("Database Creation Failed");
            }
        }
          else{
        // do nothing
            this.StBar.setStatus("Form Cancelled");
          }
    }

    final org.edu.gces.s2005.projects.frontendformysql.ui.parent.TablePanel displayTable( javax.swing.tree.DefaultMutableTreeNode node )
    {
            
        org.edu.gces.s2005.projects.frontendformysql.ui.parent.TablePanel panel = new  org.edu.gces.s2005.projects.frontendformysql.ui.parent.TablePanel( node.getParent().getParent().toString() , node.toString() , this.Engine );
        
                 panel.setParent( this );
        
                 if( panel.initialize() ) 
                 {
                     this.displayComponet( panel , node.getParent().getParent().toString() + "/" + node.toString() );
        
                 } // if ends
                 else
                     System.out.println( "could not initialize so not displaying..." );
                 return panel;
    }// func ends
    
    final void displayComponet( java.awt.Component panel, String TabTitle )
    {            
                 if( ! this.isAlreadyOpenedinTab( TabTitle ) ) { // check if table has already been opened
                 CentralTab.add( TabTitle , panel );  // adding the panel to the central tab with title viz name of database/name of table               
                 org.edu.gces.s2005.projects.frontendformysql.ui.Components.ButtonTabComponent.initTabComponent( CentralTab , CentralTab.getTabCount() -1 );
                 CentralTab.setSelectedIndex( CentralTab.getTabCount() -1 );                   
                 }
                 else
                 {
                  // do nothing                     
                 }
    }
        
    
   public boolean isAlreadyOpenedinTab( String T )
   {
        return CentralTab.indexOfTab( T ) != -1 ;             
   }
   
  
   public void removeTableTab()
   {
       if( CentralTab.getTabCount() > 0 )
       CentralTab.remove( CentralTab.getSelectedIndex() );       
   } // func ends
   
   
   
   public final boolean removeTab( String TabTitle )
   {
       for( int i=0; i< CentralTab.getTabCount(); i++ )
           if( CentralTab.getTitleAt( i ).equals( TabTitle ) ){
           CentralTab.remove( i );
           return true;
           }        
       
       return false;
   }
    
   /**
    *  NOTE:: THE FOLLOWING FUNC IS FOR SETTING THE EDIT BUTTONS ACTION FOR THE SEELECTED CENTERAL TAB COMPONENT AS EDITOR CAN BE MANY AT A TIME MAKING IT DIFFICULT FOR SETTING A SINGLE ACTION FOR EVERY EDITOR AT START. SO THIS FUNC WILL SET THE ACTION FOR THE CORRESPONDING BUTTOS.
    *  USE:: IT IS USED WHEN A TAB GETS SELECTED. 
    */
   private final boolean setEditActions(){
       try{
           org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface SelectedEditor = ( org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface ) this.CentralTab.getSelectedComponent();
           
         this.CutBtn.setAction( SelectedEditor.getActionProvider().getCutAction());
         this.Copy.setAction( SelectedEditor.getActionProvider().getCopyAction());
         this.PasteBtn.setAction( SelectedEditor.getActionProvider().getPasteAction( ));
         this.DeleteBtn.setAction( SelectedEditor.getActionProvider().getDeleteAction());        
         this.RedoBtn.setAction( SelectedEditor.getActionProvider().getRedoAction());
         this.UndoBtn .setAction( SelectedEditor.getActionProvider().getUndoAction());
         this.ReplaceBtn.setAction( SelectedEditor.getActionProvider().getReplaceAction() );
         this.FindBtn.setAction( SelectedEditor.getActionProvider().getFindAction() );
         this.ReplaceAllBtn.setAction( SelectedEditor.getActionProvider().getReplaceAllAction() );
         
        this.CutBtn.setText( "Cut" );
        this.Copy.setText( "Copy" );
        this.PasteBtn.setText( "Paste " );
        this.DeleteBtn.setText("Delete");
        
           return true;
       }
       catch( Exception e ){
           return false;
       }
   }// func ends
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CentralTab;
    private javax.swing.JButton CommitBtn1;
    private javax.swing.JButton ConnectBtn;
    private javax.swing.JButton Copy;
    private javax.swing.JButton CreateConstraintsBtn;
    private javax.swing.JButton CreateNewDatabaseBtn;
    private javax.swing.JButton CreateNewTableBtn;
    private javax.swing.JButton CreateProcBtn;
    private javax.swing.JButton CreateTriggerBtn;
    private javax.swing.JButton CreateViewBtn;
    private javax.swing.JButton CutBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DisconnectBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton FindBtn;
    private javax.swing.JButton HistoryBtn;
    private javax.swing.JButton NewBtn;
    private javax.swing.JButton OpenBtn;
    private javax.swing.JButton PasteBtn;
    private javax.swing.JButton RedoBtn;
    private javax.swing.JButton ReplaceAllBtn;
    private javax.swing.JButton ReplaceBtn;
    private javax.swing.JButton RollBackBtn1;
    private javax.swing.JButton SQLEditorBtn;
    private javax.swing.JButton SaveAsBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SelectAllBtn;
    private javax.swing.JButton TerminalBtn;
    private javax.swing.JButton TransactionStateBtn;
    private javax.swing.JButton UndoBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
    //     added variables
    
    /**
     * The engine will be initially null.
     * It will be initailized by the factory object n then given to it.
     * This has been primarily done to separate UI n Domain layer completely.
     */
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.StatusBar StBar = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.StatusBar();
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.DatabaseTree DbTree = null;
    org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame.DatabaseManager DbOperator = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame.DatabaseManager();
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame.MainFrameComponentsEnabler Enabler = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame.MainFrameComponentsEnabler();
    org.edu.gces.s2005.projects.frontendformysql.ui.Components.AboutDialog Abt = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.AboutDialog();
    // transaction window 
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.TransactionHistoryWindow TransacHistoryWindow = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.TransactionHistoryWindow( this, false );
    
    // driver manager UI
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.DriverManagerDialog DriverMan = null;
    
    //     added variables ends
    
    /**
     * This class is primarily for managing the tasks related to database only.
     * they can be creating , deleting and using the databases.
     */
    class DatabaseManager
    {
       
        public boolean useDatabase( String Db)
        {
            String Mess = null;
            if((  Mess = Engine.selectDatabase( Db ) ) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS )
            {
                
                System.out.println("\t Database Selected"+ Mess );
                return true;
            }
            else{                
                return false;
            }
        }// func ends
        
        public boolean createDatabase( String Db )
        {
            String Mess = null;
            if((  Mess = Engine.createDatabase( Db ) ) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS )
            {
                javax.swing.JOptionPane.showMessageDialog(null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ), "Database Creation Succcess", javax.swing.JOptionPane.INFORMATION_MESSAGE );                
                return true;
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null,org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess  ),  "Database Creation Failure!!", javax.swing.JOptionPane.ERROR_MESSAGE );
                return false;
            }
        }// func ends
        
        public boolean deleteDatabase( String Db)
        {
            String Mess = null;
            if((  Mess = Engine.deleteDatabase( Db ) ) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS )
            {
                javax.swing.JOptionPane.showMessageDialog(null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage(Mess), "Database Deletion Success!!", javax.swing.JOptionPane.INFORMATION_MESSAGE );                
                return true;
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage(Mess) , "Database Deletion Failure!!", javax.swing.JOptionPane.ERROR_MESSAGE );
                return false;
            }
        }
        
        
    }// class ends
    
    
    /**
     * This is the class for enabling and disabling the various components of 
     * mainframe at various events. To directly enable and disable the private
     * components of the mainframe it is made inner class of the mainframe instead
     * of making it function.
     */
    class MainFrameComponentsEnabler{
        
        
        public void onConnection(){
            // disabling tasks
            ConnectBtn.setEnabled( false );
            
            DisconnectBtn.setEnabled( true );
            SQLEditorBtn.setEnabled( true );
            CommitBtn1.setEnabled( true );
            RollBackBtn1.setEnabled( true );
            TransactionStateBtn.setEnabled( true );
            CreateNewDatabaseBtn.setEnabled( true );
            CreateNewTableBtn.setEnabled( true );
            CreateViewBtn.setEnabled( true );
            CreateConstraintsBtn.setEnabled( true );
            CreateTriggerBtn.setEnabled( true );
            CreateProcBtn.setEnabled( true );
            NewBtn.setEnabled( true );
            TerminalBtn.setEnabled( true );
            HistoryBtn.setEnabled( true );
        }

        public void onDisconnection(){
            // disabling tasks
            ConnectBtn.setEnabled( true );
            
            DisconnectBtn.setEnabled( false );
            SQLEditorBtn.setEnabled( false );
            CommitBtn1.setEnabled( false );
            RollBackBtn1.setEnabled( false );
            TransactionStateBtn.setEnabled( false );
            CreateNewDatabaseBtn.setEnabled( false );
            CreateNewTableBtn.setEnabled( false );
            CreateViewBtn.setEnabled( false );
            CreateConstraintsBtn.setEnabled( false );
            CreateTriggerBtn.setEnabled( false );
            CreateProcBtn.setEnabled( false );
            NewBtn.setEnabled( false );
            TerminalBtn.setEnabled( false );
            HistoryBtn.setEnabled( false );
            
            this.whenNotEditing();
            
        }        
        
        public void whenEditing(){
            
            OpenBtn.setEnabled( true );
            SaveBtn.setEnabled( true );
            SaveAsBtn.setEnabled( true );
            
            /**
             * Note:: initially i didnt put the below code since the method for setting
             * the action for the edit buttons also enabled it indirectly but the tasks 
             * were found to be rather uncertain.
             */
            CutBtn.setEnabled( true );
            Copy.setEnabled( true );
            PasteBtn.setEnabled( true );
            PasteBtn.setEnabled( true );
            DeleteBtn.setEnabled( true );
            ReplaceBtn.setEnabled( true );
            ReplaceAllBtn.setEnabled( true );
            FindBtn.setEnabled( true );
            SelectAllBtn.setEnabled( true );
            UndoBtn.setEnabled( true );
            RedoBtn.setEnabled( true );            
            
        }
        
        public void whenNotEditing(){
            
            OpenBtn.setEnabled( false );
            SaveBtn.setEnabled( false );
            SaveAsBtn.setEnabled( false );
            
            CutBtn.setEnabled( false );
            Copy.setEnabled( false );
            PasteBtn.setEnabled( false );
            PasteBtn.setEnabled( false );
            DeleteBtn.setEnabled( false );
            ReplaceBtn.setEnabled( false );
            ReplaceAllBtn.setEnabled( false );
            FindBtn.setEnabled( false );
            SelectAllBtn.setEnabled( false );
            UndoBtn.setEnabled( false );
            RedoBtn.setEnabled( false );            
         
        }
        
    }
    
}
