
//                        !! RAM !!

/**
 * ProcedureBuilderPanel.java
 *
 * Created on October 16, 2007, 9:47 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.parent;


import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeListener;
import org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditorInterface;


/***
 *
 * @author sumit
 */
public class ProcedureBuilderPanel extends javax.swing.JPanel implements SQLEditorInterface {
    
    /*** Creates new form ProcedureBuilderPanel */
    public ProcedureBuilderPanel( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd eng, String D ) {
        
        this.Engine = eng;
        
        this.Db = D;
        
        initComponents();
                
        this.RunBtn.setEnabled( false );
    }
    
    /**
     * other initializer for constructing procedure builder when proc is read from server n already exists.
     */
    public ProcedureBuilderPanel( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ProcedureInterface Proc , org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd eng, String D ){
        
        this.Engine = eng;
        
        this.Db = D;
                
        initComponents();
        
        this.NameText.setText( Proc.getName() );
        
        if( Proc.getParameters() == null ){
            return;
        }
        
        addParameters(Proc);
        
        this.onCompilation();
    }

    private void addParameters(final org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ProcedureInterface Proc) {
        
        for( int i= 0; i< Proc.getParameters().length; i++ ){        
        String[] addarray = new String[3];
        
        addarray[0] = Proc.getParameters()[i].getAttName();
        addarray[1] = Proc.getParameters()[i].getAttType();
        addarray[2] = String.valueOf( Proc.getParameters()[i].getAttSize() ) ;
        
        this.ParamTableModel.addRow( addarray );
        }
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JPanel EditorPanel;
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel3;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel3;
        javax.swing.JScrollPane jScrollPane1;
        javax.swing.JTabbedPane jTabbedPane1;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CommentText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ParamTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        EditorPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        RunBtn = new javax.swing.JButton();
        CompileBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel1, gridBagConstraints);

        NameText.setColumns(100);
        NameText.setMinimumSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(NameText, gridBagConstraints);

        jLabel2.setText("Comment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        CommentText.setColumns(100);
        CommentText.setMinimumSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel1.add(CommentText, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 200));
        ParamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Size"
            }
        ));
        this.ParamTableModel = ( javax.swing.table.DefaultTableModel ) this.ParamTable.getModel();

        javax.swing.table.TableColumn TypeColumn = this.ParamTable.getColumnModel().getColumn( 1 );

        javax.swing.JComboBox comboBox = new javax.swing.JComboBox();
        String[] list = this.Engine.getDatabaseReader().getSupportedTypesList();
        if( list != null){
            for( int i=0 ;i< list.length; i++ ){
                comboBox.addItem( list[i] );
            }

            TypeColumn.setCellEditor(new javax.swing.DefaultCellEditor(comboBox));
        }
        jScrollPane1.setViewportView(ParamTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel3.setText("Parameters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 10);
        jPanel1.add(jButton2, gridBagConstraints);

        jButton3.setText("DROP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(53, 0, 0, 8);
        jPanel1.add(jButton3, gridBagConstraints);

        jTabbedPane1.addTab("Procedure Info", jPanel1);

        EditorPanel.setLayout(new java.awt.BorderLayout());

        this.EditorText = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditor( this.Engine.getIOManager() );

        javax.swing.JScrollPane Pane = new javax.swing.JScrollPane( this.EditorText );

        EditorPanel.add( Pane );
        jTabbedPane1.addTab("Editor", EditorPanel);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        RunBtn.setText("RUN");
        RunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(RunBtn, gridBagConstraints);

        CompileBtn.setText("COMPILE");
        CompileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompileBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 240, 0, 0);
        jPanel3.add(CompileBtn, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

    private void RunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunBtnActionPerformed
        String Mess;
        if( ( Mess = this.Engine.ExecuteProcedure( this.getProcedure() ) ).equals(org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ) ){
            new org.edu.gces.s2005.projects.frontendformysql.ui.Components.ResultSetViewer( null , this.Engine.getResultSet() );
        }
        else{
            javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ), " Procedure Execution Failure!!", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_RunBtnActionPerformed

    private void CompileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompileBtnActionPerformed
        String Mess = null;
        if( ( Mess = Engine.compileProcedure( this.getProcedure() ) )  == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
            onCompilation();
            javax.swing.JOptionPane.showMessageDialog( this, "Procedure was successfully compiled","Procedure Compiled Successfully", javax.swing.JOptionPane.INFORMATION_MESSAGE );
        }
        else{
            javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ),"Procedure Compiled Failure", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_CompileBtnActionPerformed

    private void onCompilation() throws HeadlessException {
        this.CompileBtn.setEnabled( false );
        this.RunBtn.setEnabled( true );        
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if( this.ParamTable.getSelectedRow() != -1 ){
            this.ParamTableModel.removeRow( this.ParamTable.getSelectedRow() );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object[] add = new Object[3];
        this.ParamTableModel.addRow( add );
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ProcedureInterface getProcedure(){
        return ( new org.edu.gces.s2005.projects.frontendformysql.ui.parent.ProcedureBuilderPanel.ProcedureCoverter() );
    }// func ends
      
    public org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.Edit.DocEditActionProvider getActionProvider(){
        return this.EditorText.getActionProvider();
    }
    
    public org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.File.FileManager getManager(){
        return this.EditorText.getFileManager();
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommentText;
    private javax.swing.JButton CompileBtn;
    private javax.swing.JTextField NameText;
    private javax.swing.JTable ParamTable;
    private javax.swing.JButton RunBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.DocumentEditor.SQLEditor EditorText = null;
    private javax.swing.table.DefaultTableModel ParamTableModel = null;
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine= null;
    private String Db = null;    
    
    private class ProcedureCoverter implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ProcedureInterface {       
    
    public String getName(){
        return NameText.getText();
    }
    
    public String getComment(){
        return CommentText.getText();
    }
    
    public String getOperation(){
        return EditorText.getText();
    }
    
    public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] getParameters(){
        if( ParamTable.getRowCount() < 1)
            return ( new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[0] );
        
        // else
        int NameColl = 0;
        int TypeColl = 1;
        int SizeColl = 2;
        
        org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] array = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute [ ParamTable.getRowCount() ];
        
        for( int i=0 ;i< ParamTable.getRowCount(); i++ ){            
            try{
            array[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute();
            array[i].setName( ParamTable.getValueAt( i, NameColl ).toString() );
            array[i].setType( ParamTable.getValueAt( i, TypeColl ).toString() );
            array[i].setSize( Integer.parseInt( ParamTable.getValueAt( i, SizeColl ).toString() ) );
            }
            catch( Exception e){
                System.out.println( e );
            }
            }        
        return array;
    }
   
    public String getDatabase(){
        return Db;
    }
    
    
    }// inner class ends
    
}