
//                             !! RAM !!

/**
 * SQLTerminal.java
 *
 * Created on October 30, 2007, 9:18 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.parent;

/***
 *
 * @author  sumit
 */
public class SQLTerminal extends javax.swing.JPanel {
    
    /*** Creates new form SQLTerminal */
    public SQLTerminal( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        this.Engine = Engine;
        initComponents();
        this.InputText.requestFocusInWindow();
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        InputText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayText = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);
        InputText.setFont(new java.awt.Font("Monospac821 BT", 0, 14));
        InputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTextActionPerformed(evt);
            }
        });
        InputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InputTextKeyPressed(evt);
            }
        });

        jSplitPane1.setBottomComponent(InputText);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        DisplayText.setEditable(false);
        jScrollPane1.setViewportView(DisplayText);

        jSplitPane1.setLeftComponent(jScrollPane1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void InputTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputTextKeyPressed
        if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP ){            
            this.onUpArrowPressed();
        }
        else
            if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN ){
                this.onDownArrowPressed();
            }
    }//GEN-LAST:event_InputTextKeyPressed

    private void InputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTextActionPerformed
        String IpText = this.InputText.getText();
        
        // add to list for future references
        this.QueryList.setStatus( IpText );
        
        int end = IpText.indexOf( this.Delimiter );
        
        // check if there is delimiter
        if( end != -1 ){ 
            this.ExecuteQuery += " " + IpText.substring( 0, end ) + ";";       
            this.addText( IpText.substring( 0, end ) );
            this.InputText.setText( "" );
            this.executeQuery();
            this.ExecuteQuery = "";
        }
        else{
            addText( IpText );
            this.ExecuteQuery += " " + IpText + " ";
            this.InputText.setText( "" );
        }
    }//GEN-LAST:event_InputTextActionPerformed
        
    private final void addText( String Text ){
        // prepare text
        String T = "";
        try{
        T= "\n"+ this.Engine.getUserManager().getPresentUser().getUserName();
        }
        catch( java.lang.NullPointerException e ){
            T = "\nUser";
        }
        
        try{           
            this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() , T, this.FontProperties.getUserNameAttributes() );
            this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() , " >> ", this.FontProperties.getUserDoubleArrowAttributes() );
            this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() ,  Text, this.FontProperties.getUserTextAttributes() );
        }
        catch( javax.swing.text.BadLocationException e ){
            System.out.println( e );
        }
    }
    
    private final void addServerReply( final String mess ){
        
        try{
            String T = "\n\nServer";
            this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() , T, this.FontProperties.getServerNameAttributes() );
            this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() , " >> ", this.FontProperties.getServerDoubleArroweAttributes() );
            if( mess == this.ErrorMess ){
                  this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() ,mess + "\n", this.FontProperties.getServerErrorAttributes() );
             }
            else{
                 this.DisplayText.getDocument().insertString( this.DisplayText.getDocument().getLength() , mess + "\n", this.FontProperties.getServerOKAttributes() );
            }
            
        }
        catch( javax.swing.text.BadLocationException e ){
            System.out.println( e );
        }
    }
    
    private void executeQuery(){
        final String State = this.Engine.execute( this.ExecuteQuery );
        if( State == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
            // get rs
            java.sql.ResultSet Rs = this.Engine.getQueryResult();
            if( Rs == null ){ // for update query
                this.addServerReply( this.NonResultMess );                
            }
            else{
                this.addServerReply( this.ResultMess );                
                this.ResultDisplay.displayResultSet( Rs );
            }
        }
        else{
            this.addServerReply( this.ErrorMess );
            javax.swing.JOptionPane.showMessageDialog( null, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( State ), "Execution Failure", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }
    
    public void onUpArrowPressed(){
        try{
            /**
            if( this.QueryList.reachedFirstMostRecent() ){
                String s = this.QueryList.getRecentStatus();
                
                if( s != this.QueryList.NO_NEXT ){
                    this.InputText.setText( s );
                }
                else
                    java.awt.Toolkit.getDefaultToolkit().beep();
                
                return;
            }
            */
            String State = this.QueryList.getPreviousStatus();
            if( State != this.QueryList.NO_PREVIOUS ){
                this.InputText.setText( State );
            }
            else
                java.awt.Toolkit.getDefaultToolkit().beep();
        }
        catch( java.lang.IndexOutOfBoundsException e ){            
            java.awt.Toolkit.getDefaultToolkit().beep();
        }                
    }// func ends
    
    public void onDownArrowPressed(){
        try{
            String State = this.QueryList.getNextStatus();
            if( State != this.QueryList.NO_NEXT ){
                this.InputText.setText( State );            
            }
            else
                java.awt.Toolkit.getDefaultToolkit().beep();
        }
        catch( java.lang.IndexOutOfBoundsException e ){            
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }// func ends
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane DisplayText;
    private javax.swing.JTextField InputText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;
    public static final char Delimiter = ';';
    private String ExecuteQuery = "";
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.TerminalFontPropertiesUtility FontProperties = new org.edu.gces.s2005.projects.frontendformysql.ui.parent.TerminalFontPropertiesUtility();
    // display window 
    private org.edu.gces.s2005.projects.frontendformysql.ui.Components.ResultSetViewer ResultDisplay = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.ResultSetViewer( null );
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DataStructures.StatusBarDataStructure QueryList = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DataStructures.StatusBarDataStructure( 100 );
    
    // some constants;
    private final String NonResultMess = "Done";
    private final String ResultMess = "Done And Shown";
    private final String ErrorMess = "Error Cannot Execute";
}


class TerminalFontPropertiesUtility{
    public TerminalFontPropertiesUtility(){
       this.setServerErrorAttributes();
       this.setServerOKAttributes();
       this.setUserTextAttributes();
       this.setServerNameAttr();
       this.setUserNameAttributes();
       this.setUserDoubleArrowAttr();
       this.setServerDoubleArrayAtt();
    }
    
    private void setUserTextAttributes(){
        UserTextAttributes = new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily(UserTextAttributes, "SansSerif" );
        javax.swing.text.StyleConstants.setFontSize( UserTextAttributes, 18 );
        javax.swing.text.StyleConstants.setItalic( UserTextAttributes, true );
        javax.swing.text.StyleConstants.setForeground( UserTextAttributes, java.awt.Color.BLUE );                
    }
    
    private void setUserNameAttributes(){
        this.UserNameAttributes = new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily( this.UserNameAttributes, "Monospaced" );
        javax.swing.text.StyleConstants.setFontSize( this.UserNameAttributes , 18 );
        javax.swing.text.StyleConstants.setBold( this.UserNameAttributes, true );
        javax.swing.text.StyleConstants.setUnderline( this.UserNameAttributes, true );
        javax.swing.text.StyleConstants.setForeground( this.UserNameAttributes, java.awt.Color.RED );
    }
    
    private void setUserDoubleArrowAttr(){
        this.UserDoubleArrowAttribute = new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily( this.UserDoubleArrowAttribute, "Monospaced" );
        javax.swing.text.StyleConstants.setFontSize( this.UserDoubleArrowAttribute, 18 );
        javax.swing.text.StyleConstants.setBold( this.UserDoubleArrowAttribute, true );        
        javax.swing.text.StyleConstants.setForeground( this.UserDoubleArrowAttribute, java.awt.Color.RED );
    }    
    
    private void setServerErrorAttributes(){
        ServerErrorAttributes= new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily(ServerErrorAttributes, "Arial" );
        javax.swing.text.StyleConstants.setFontSize( ServerErrorAttributes, 16 );
        javax.swing.text.StyleConstants.setBold( ServerErrorAttributes, true);
        javax.swing.text.StyleConstants.setForeground( ServerErrorAttributes, java.awt.Color.ORANGE );              
    }
    
    private void setServerOKAttributes(){
        ServerOKAttributes = new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily( ServerOKAttributes, "Arial" );
        javax.swing.text.StyleConstants.setFontSize( ServerOKAttributes, 16 );        
        javax.swing.text.StyleConstants.setForeground( ServerOKAttributes, java.awt.Color.GREEN );
    }
    
    private void setServerNameAttr(){
        this.ServerNameAttributes = new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily( this.ServerNameAttributes, "Monospaced" );
        javax.swing.text.StyleConstants.setFontSize( ServerNameAttributes, 16 );
        javax.swing.text.StyleConstants.setBold( ServerNameAttributes, true);
        javax.swing.text.StyleConstants.setUnderline( ServerNameAttributes, true);
        javax.swing.text.StyleConstants.setForeground( ServerNameAttributes, java.awt.Color.BLACK );
    }
    
    private void setServerDoubleArrayAtt(){
        this.ServerDoubleArrowAttribute = new javax.swing.text.SimpleAttributeSet();
        javax.swing.text.StyleConstants.setFontFamily( this.ServerDoubleArrowAttribute, "Monospaced" );
        javax.swing.text.StyleConstants.setFontSize( this.ServerDoubleArrowAttribute, 16 );
        javax.swing.text.StyleConstants.setBold( this.ServerDoubleArrowAttribute, true);        
        javax.swing.text.StyleConstants.setForeground( this.ServerDoubleArrowAttribute, java.awt.Color.BLACK );
    }
    
    public javax.swing.text.AttributeSet getUserTextAttributes(){
        return this.UserTextAttributes;
    }   
    
    public javax.swing.text.AttributeSet getUserNameAttributes(){
        return this.UserNameAttributes;
    }   
        
    public javax.swing.text.AttributeSet getServerOKAttributes(){
        return this.ServerOKAttributes;
    }   
    
    public javax.swing.text.AttributeSet getServerErrorAttributes(){
        return this.ServerErrorAttributes;
    }   
    
    public javax.swing.text.AttributeSet getServerNameAttributes(){
        return this.ServerNameAttributes;
    }   
    
    public javax.swing.text.AttributeSet getUserDoubleArrowAttributes(){
        return this.UserDoubleArrowAttribute;
    }   
    
    public javax.swing.text.AttributeSet getServerDoubleArroweAttributes(){
        return this.ServerDoubleArrowAttribute;
    }   
    
    private javax.swing.text.SimpleAttributeSet UserTextAttributes;
    private javax.swing.text.SimpleAttributeSet UserNameAttributes;
    private javax.swing.text.SimpleAttributeSet ServerOKAttributes;
    private javax.swing.text.SimpleAttributeSet ServerErrorAttributes;
    private javax.swing.text.SimpleAttributeSet ServerNameAttributes;
    private javax.swing.text.SimpleAttributeSet UserDoubleArrowAttribute;
    private javax.swing.text.SimpleAttributeSet ServerDoubleArrowAttribute;
    
}// utility class ends
