
//                                               !! RAM !!

/**
 * TablePanel.java
 *
 * Created on August 4, 2007, 9:37 AM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.parent;

import java.awt.HeadlessException; 


/***
 *
 * @author  sumit sherstha
 */
public class TablePanel extends javax.swing.JPanel implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableValueChange, org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableInterface, org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TransactionListener {
    
    /*** Creates new form TablePanel */
    public TablePanel( String DB , String Tb, org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd eng ) {
        this.DatabaseNm = DB;
        this.Title = Tb;
        this.Engine = eng;        
        
        // add lisener
        this.Engine.getTransactionManager().addTransactionListener( this );
        
        initComponents();        
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JPanel jPanel10;
        javax.swing.JPanel jPanel9;
        javax.swing.JScrollPane jScrollPane3;
        javax.swing.JScrollPane jScrollPane4;
        javax.swing.JSplitPane jSplitPane3;

        jPanel3 = new javax.swing.JPanel();
        MainTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        NorthPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        AddDataBtn = new javax.swing.JButton();
        DelDataBtn = new javax.swing.JButton();
        LimitCheck = new javax.swing.JCheckBox();
        LimitIP = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        AttAddBtn = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        DelTableAttBtn = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AttTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel9 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        ForeignKeyDropBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ForeignKey = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        TrigAddBtn = new javax.swing.JButton();
        TrigEditBtn = new javax.swing.JButton();
        TrigDropBtn = new javax.swing.JButton();
        TrigRefreshBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TrigTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        MainTab.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(40, 40));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        //Table.setModel( TableModel );
        TableModel = ( javax.swing.table.DefaultTableModel ) Table.getModel();
        for( int i=0 ;i< Table.getColumnCount(); i++)
        Table.getColumn( Table.getColumnName( i ) ).setResizable( true );

        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("First");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Prior");

        jButton3.setText("Next");

        jButton4.setText("Last");

        AddDataBtn.setText("++");
        AddDataBtn.setNextFocusableComponent(Table);
        AddDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataBtnActionPerformed(evt);
            }
        });

        DelDataBtn.setText("--");
        DelDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelDataBtnActionPerformed(evt);
            }
        });

        LimitCheck.setSelected(true);
        LimitCheck.setText("Size Limit");
        LimitCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        LimitCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        LimitCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimitCheckActionPerformed(evt);
            }
        });

        LimitIP.setText("100");

        jButton7.setText("Edit");

        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NorthPanelLayout = new javax.swing.GroupLayout(NorthPanel);
        NorthPanel.setLayout(NorthPanelLayout);
        NorthPanelLayout.setHorizontalGroup(
            NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthPanelLayout.createSequentialGroup()
                .addGroup(NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(NorthPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(NorthPanelLayout.createSequentialGroup()
                        .addComponent(LimitCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LimitIP)))
                .addGap(130, 130, 130)
                .addGroup(NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NorthPanelLayout.createSequentialGroup()
                        .addComponent(AddDataBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jButton8))
                    .addComponent(jButton7)))
        );
        NorthPanelLayout.setVerticalGroup(
            NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthPanelLayout.createSequentialGroup()
                .addGroup(NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(DelDataBtn)
                    .addComponent(AddDataBtn)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimitCheck)
                    .addComponent(LimitIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1.add(NorthPanel, java.awt.BorderLayout.NORTH);

        MainTab.addTab("Data", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        AttAddBtn.setText("Add");
        AttAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttAddBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel6.add(AttAddBtn, gridBagConstraints);

        jButton10.setText("Edit");
        jButton10.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 19, 0);
        jPanel6.add(jButton10, gridBagConstraints);

        DelTableAttBtn.setText("Drop");
        DelTableAttBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelTableAttBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 0);
        jPanel6.add(DelTableAttBtn, gridBagConstraints);

        jButton12.setText("++");
        jButton12.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 17, 0);
        jPanel6.add(jButton12, gridBagConstraints);

        jButton13.setText("Refresh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanel6.add(jButton13, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        AttTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Field", "Type", "Key", "Size", "Null", "Default"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableAttModel = ( javax.swing.table.DefaultTableModel ) AttTable.getModel();

        for( int i=0 ;i< AttTable.getColumnCount(); i++)
        AttTable.getColumn( AttTable.getColumnName( i ) ).setResizable( true );

        jScrollPane2.setViewportView(AttTable);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel7);

        jPanel2.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        MainTab.addTab("Collumns", jPanel2);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jButton14.setText("Add");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPanel9.add(jButton14, gridBagConstraints);

        ForeignKeyDropBtn.setText("Drop");
        ForeignKeyDropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeignKeyDropBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(89, 0, 5, 0);
        jPanel9.add(ForeignKeyDropBtn, gridBagConstraints);

        jSplitPane2.setLeftComponent(jPanel9);

        jPanel11.setLayout(new java.awt.BorderLayout());

        ForeignKey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "PK_Catalog", "PK_Table", "PK_Name", "deleteRule", "updateRule", "Deferability", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableForeignKeyModel = ( javax.swing.table.DefaultTableModel ) ForeignKey.getModel();
        /**
        for( int i=0; i< this.ForeignKey.getColumnCount(); i++ )
        this.ForeignKey.getColumn( i ).setResizable( true );
        */

        jScrollPane3.setViewportView(ForeignKey);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel11);

        jPanel8.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        MainTab.addTab("Foreign Key", jPanel8);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.GridBagLayout());

        TrigAddBtn.setText("ADD");
        TrigAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrigAddBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel10.add(TrigAddBtn, gridBagConstraints);

        TrigEditBtn.setText("Edi");
        TrigEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrigEditBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel10.add(TrigEditBtn, gridBagConstraints);

        TrigDropBtn.setText("Drop");
        TrigDropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrigDropBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel10.add(TrigDropBtn, gridBagConstraints);

        TrigRefreshBtn.setText("Refresh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel10.add(TrigRefreshBtn, gridBagConstraints);

        jSplitPane3.setLeftComponent(jPanel10);

        TrigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Statement", "Event", "Timing", "Created"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TriggerTableModel = ( javax.swing.table.DefaultTableModel )this.TrigTable.getModel();

        javax.swing.table.TableColumn TypeColumn = TrigTable.getColumnModel().getColumn( 3 );
        javax.swing.JComboBox timecomboBox = new javax.swing.JComboBox();
        timecomboBox.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.BEFORE );
        timecomboBox.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.AFTER );
        TypeColumn.setCellEditor(new javax.swing.DefaultCellEditor(timecomboBox));

        javax.swing.table.TableColumn EventColumn = TrigTable.getColumnModel().getColumn( 2 );
        javax.swing.JComboBox evtcomboBox = new javax.swing.JComboBox();
        evtcomboBox.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.INSERT );
        evtcomboBox.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.DELETE );
        evtcomboBox.addItem( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger.UPDATE );
        EventColumn.setCellEditor(new javax.swing.DefaultCellEditor( evtcomboBox));

        for( int i=0 ;i< TrigTable.getColumnCount(); i++)
        TrigTable.getColumn( TrigTable.getColumnName(i) ).setResizable( true );

        jScrollPane4.setViewportView(TrigTable);

        jSplitPane3.setRightComponent(jScrollPane4);

        jPanel4.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        MainTab.addTab("Triggers", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        MainTab.addTab("Scripts", jPanel5);

        add(MainTab, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void TrigDropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrigDropBtnActionPerformed
        int index = this.TrigTable.getSelectedRow();
        
        if( index > -1 ){
            // create a anonymous class for delete event
            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TriggerChangeInterface TriggDropEvt = 
                    new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TriggerChangeInterface(){
                        public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableTriggerInterface getChangedTrigger(){
                            
                            final int TRIGG_INDEX = TrigTable.getSelectedRow();
                            final int TRIGG_NAME = 0;
                            final int TRIGG_STATEMENT = 1;
                            final int TRIGG_EVENT = 2;
                            final int TRIGG_TIMING = 3;
                            
                            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger Trigg 
                                    = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableTrigger( TrigTable.getValueAt( TRIGG_INDEX, TRIGG_NAME ).toString() );
                            Trigg.setOperation( TrigTable.getValueAt( TRIGG_INDEX, TRIGG_STATEMENT ).toString() );
                            Trigg.setEvent( TrigTable.getValueAt( TRIGG_INDEX, TRIGG_EVENT ).toString() );
                            Trigg.setTiming( TrigTable.getValueAt( TRIGG_INDEX, TRIGG_TIMING ).toString() );
                            
                            return Trigg;
                        }
    
                        public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableTriggerInterface getNewTrigger(){
                            return null;// no need
                        }
    
                        public String getChangedTableName(){
                            return Title;
                        }
    
                        public String getTriggerDatabase(){
                            return DatabaseNm;
                        }
            };
            
            String Mess = this.Engine.dropTrigger( TriggDropEvt );
            if( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
                this.reinitialize();
                javax.swing.JOptionPane.showMessageDialog( this, "Trigger successfully deleted " , "Trigger drop Success" , javax.swing.JOptionPane.INFORMATION_MESSAGE );                
            }
            else{
                javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ), "Trigger Drop Failed" , javax.swing.JOptionPane.ERROR_MESSAGE );
            }
            
        }
        else
        {
            // check if table has any triggers in it i.e. any row is present
            if( this.TrigTable.getRowCount() > 0 )
            javax.swing.JOptionPane.showMessageDialog( this, "Please select the row to be deleted " , "Table Row Not Selected" , javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_TrigDropBtnActionPerformed

    private void TrigEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrigEditBtnActionPerformed
        makeTriggerTableEditable();
    }//GEN-LAST:event_TrigEditBtnActionPerformed
    
    public void makeTriggerTableEditable(){
        
    }
    
    private void TrigAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrigAddBtnActionPerformed
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.addTriggerForm form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.addTriggerForm( this.parent , true, this.Title, this.DatabaseNm );
        if( form.display() ){
            String Mess =  this.Engine.addTrigger( form.getTriggerAdditionEvent() );
            if ( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){                
                this.addTrigger( form.getTriggerAdditionEvent().getNewTrigger() );
                this.reinitialize();
                javax.swing.JOptionPane.showMessageDialog(this, "Congratulation!! \n\t The Trigger was successfully added.","TRIGGER ADDITION SUCCESS",javax.swing.JOptionPane.INFORMATION_MESSAGE );
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this,org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ),"TRIGGER ADDITION Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        }
    }//GEN-LAST:event_TrigAddBtnActionPerformed
    
    private void addTrigger( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableTriggerInterface Trigg ){
        String[] array = new String[5];
        try{
        array[0] = Trigg.getName();
        }
        catch( Exception e ){
            System.out.println( " exception while adding name " + e );
            return; // return since there cannot be a trigger without a name
        }
        try{
        array[1] = Trigg.getOperation();        
        }
        catch( Exception e ){
            System.out.println( " exception while adding  operation" + e );
        }
        try{
        array[2] = Trigg.getEvent();
        }
        catch( Exception e ){
            System.out.println( " exception while adding  evnet" + e );
        }
        try{
        array[3] = Trigg.getTiming();
        }
        catch( Exception e ){
            System.out.println( " exception while adding  time" + e );
        }
        array[4] = "Date";        
        
        this.TriggerTableModel.addRow( array );
    }
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.reinitialize();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LimitCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimitCheckActionPerformed
// TODO add your handling code here:
        if( ! LimitCheck.isSelected() )
        {
           LimitIP.setEnabled( false );
        }
        else
        {
            LimitIP.setEnabled( true );
        }
    }//GEN-LAST:event_LimitCheckActionPerformed

    private void DelDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelDataBtnActionPerformed
// TODO add your handling code here:
        
        int SelRow = Table.getSelectedRow();
       
        if( SelRow > -1 ){
            String Mess =  Engine.deleteTableData( this );
            if ( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
                TableModel.removeRow( SelRow );
                javax.swing.JOptionPane.showMessageDialog(this, "The Tuple is deleted","Tuple Delection Success",javax.swing.JOptionPane.INFORMATION_MESSAGE );
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this, Mess ,"Tuple Deletion Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Tuple wasnt selected\nSelect your Tuple First","Tuple Selection Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_DelDataBtnActionPerformed

    private void AddDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataBtnActionPerformed
        addTableData();
    }//GEN-LAST:event_AddDataBtnActionPerformed

    public void addTableData() throws HeadlessException {        
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.InsertValuesInTable ValueIpForm = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.InsertValuesInTable( parent , true); // just testing for null parent
        ValueIpForm.setTypes( this.returnCollumnNames() );
        if( ValueIpForm.setVisible() ){
             Object[] Val = ValueIpForm.returnValuesInserted();
             
             setInsertedValues( Val ); // set values to be inserted
             
             // then simply tell the backend to insert values
             String Mess = Engine.insertTableData( this ) ;
             if ( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
                 
                // insert the row into table model
                TableModel.addRow( Val );  
                
                javax.swing.JOptionPane.showMessageDialog( parent , "The Tuple was inserted","Tuple Insertion Success",javax.swing.JOptionPane.INFORMATION_MESSAGE );
                
                // note:: no need to make a pointer of the tuple where value was inserted.
             }
             else
             {
                    // report user of failure
                    javax.swing.JOptionPane.showMessageDialog( parent , org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ) ,"Tuple Insertion Faillure",javax.swing.JOptionPane.ERROR_MESSAGE );
             }
             
             
        }// if ends
        else
        {
            // do nothing as user cancelled insert values
            
        }
    }

    
    private void DelTableAttBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelTableAttBtnActionPerformed
// TODO add your handling code here:
        if( ! ( javax.swing.JOptionPane.showConfirmDialog( this, "Are You Sure You Want to Delete the Selected Attribute from the Table","Table Attribute Deletion Cofirmation",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.WARNING_MESSAGE ) == javax.swing.JOptionPane.OK_OPTION ) )
            return; // do nothing then
        
        // else
         org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeChangedInterface DelAttEvent = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeChangedInterface()
         {
            
            public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] getNewAttributesValues(){
                return null;
            }// not needed
            
            public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table getChangedTable(){
                org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table Tb = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table();
                Tb.setName( Title );
                return Tb;
            }
          
            public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] getChangedAttributes()
            {
                org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] ChangeAtt = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[ 1 ];
              try{  
                ChangeAtt[0] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute();
                ChangeAtt[0].setName( (String)TableAttModel.getValueAt( AttTable.getSelectedRow(), getAttTableCollIndex( "Field" ) ) );
                ChangeAtt[0].setType( (String) TableAttModel.getValueAt( AttTable.getSelectedRow(),getAttTableCollIndex( "Type" ) )  );
                ChangeAtt[0].setKey( (String)TableAttModel.getValueAt(AttTable.getSelectedRow(), getAttTableCollIndex( "Key" ) ) );
                ChangeAtt[0].setSize( Integer.parseInt( (String) TableAttModel.getValueAt(AttTable.getSelectedRow(), getAttTableCollIndex( "Size" ) ) ) );
                ChangeAtt[0].setNullable( TableAttModel.getValueAt(AttTable.getSelectedRow(), getAttTableCollIndex( "Null" ) ) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableInterface.NULL  );
                ChangeAtt[0].setDefaultValue( (String) TableAttModel.getValueAt(AttTable.getSelectedRow(), getAttTableCollIndex( "Default" ) ) );
              }
              catch( Exception e )
              {                  
                  System.out.println( e );
                  return null;
              }
                
                return ChangeAtt;
            }
            
         };// interface defn body ends
         
        
        String Mess = Engine.deleteTableAtt( DelAttEvent );
         if( Mess  == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
             javax.swing.JOptionPane.showMessageDialog( this, Mess ,"table att delete success", javax.swing.JOptionPane.INFORMATION_MESSAGE );
             
            // atlast refresh the UI
             this.reinitialize();
         }
         else
         {
              javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ) ,"table att delete Failure", javax.swing.JOptionPane.ERROR_MESSAGE );
         }
    }//GEN-LAST:event_DelTableAttBtnActionPerformed

    private void ForeignKeyDropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeignKeyDropBtnActionPerformed
        
        final int INDEX = this.ForeignKey.getSelectedRow();
        
        final int FORKEY_NAME = 0;
        final int PK_DB= 1;
        final int PK_TABLE = 2;
        final int PK_NAME = 3;
        final int DEL_RULE = 4;
        final int UPDATE_RULE = 5;
        final int DEFERABILITY = 6;
        final int COMMENT = 7;
        
        if( INDEX > -1 ){
            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyChangeInterface ForKeyDropEvt
                    = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyChangeInterface(){
                        
                        public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface getNewForeignKey(){
                            return null; // not needed
                        }
                        
                        public String getChangedTable(){
                            return Title;
                        }
                        
                        public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface getChangedForeignKey(){
                            
                            String  ForKeyName = ForeignKey.getValueAt( INDEX, FORKEY_NAME ).toString();
                            
                            if( ForKeyName == null ){
                                return null; // no for key without name
                            }
                            
                            org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key ForKey
                                    = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Foreign_key( ForKeyName );
                            try{
                            ForKey.setPk_Database( ForeignKey.getValueAt( INDEX, PK_DB ).toString() );
                            ForKey.setPk_Table( ForeignKey.getValueAt( INDEX, PK_TABLE ).toString() );
                            ForKey.setPK_Name( ForeignKey.getValueAt( INDEX, PK_NAME ).toString() );
                            ForKey.setDelete_Rule( ForeignKey.getValueAt( INDEX, DEL_RULE ).toString() );
                            ForKey.setUpdate_Rule( ForeignKey.getValueAt( INDEX, UPDATE_RULE ).toString() );
                            ForKey.setDeferability_Rule( ForeignKey.getValueAt( INDEX, DEFERABILITY ).toString() );
                            }
                            catch( Exception e ){                                
                            }
                            
                            return ForKey;
                        }                        
                    };
                    
                    String Mess = this.Engine.dropForeignKey( ForKeyDropEvt );
                    
                    if( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
                        this.reinitialize();
                        javax.swing.JOptionPane.showMessageDialog( this, "The Foreign key was successfully deleted", "FOREIGN KEY DELETION SUCCESS", javax.swing.JOptionPane.INFORMATION_MESSAGE );
                    }
                    else{
                        javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage (Mess) , "FOREIGN KEY DELETION FAILURE", javax.swing.JOptionPane.ERROR_MESSAGE );
                    }
                    
        }
        else{
            if( this.ForeignKey.getRowCount() > 0 ){
                javax.swing.JOptionPane.showMessageDialog( this, "Please select the required foreign key to drop", "Foreign key not Selected", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        }
    }//GEN-LAST:event_ForeignKeyDropBtnActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.addForeignKeyForm form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.addForeignKeyForm( this.parent, this.Engine.getDatabaseReader().readDatabase( this.DatabaseNm ), this.Title );
        if( form.display() ){
            String Mess = null;
            if( ( Mess = this.Engine.addForeignKey( form.getForeignKeyAddEvent() )) == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ){
                org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface[] array = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface[1];
                array[0] = form.getForeignKeyAddEvent().getNewForeignKey();
                this.setForeignKeys( array );
                javax.swing.JOptionPane.showMessageDialog( this, " The Foreign Key has been added", " Foreing Key Addition Success!!", javax.swing.JOptionPane.INFORMATION_MESSAGE );
            }
            else{
                javax.swing.JOptionPane.showMessageDialog( this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage ( Mess ), " Foreing Key Addition Failure!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        } 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void AttAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttAddBtnActionPerformed
        addTableColumn();
    }//GEN-LAST:event_AttAddBtnActionPerformed

    public void addTableColumn() throws HeadlessException {

        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.InsertTableCollForm form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.InsertTableCollForm( parent, Title, this.Engine.getDatabaseReader().getSupportedTypesList() );
        if( form.display() ){
           org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TableAttributeInterface[] AddAtt = null;
           AddAtt = form.getTableCollChangeEvent().getNewAttributesValues();            
           
           String Mess = Engine.insertTableAtt( form.getTableCollChangeEvent() );
           
           if( Mess == org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS ) {
               
               // refresh the table
               this.reinitialize();
               
               // report user
               javax.swing.JOptionPane.showMessageDialog(this, "Attribute was successfully added.", "Attribute Addition Success !!", javax.swing.JOptionPane.INFORMATION_MESSAGE );
               
           }   
           else
           {
               javax.swing.JOptionPane.showMessageDialog(this,org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage( Mess ), "Attribute Addition Failure !!", javax.swing.JOptionPane.ERROR_MESSAGE );
           }
        }
    }
    
 public String getDatabaseName(){
     return this.DatabaseNm;
 }
    /**
     * this func is used to remove  the old val that has to be refreshed.
     */
    
    private void resetTable()
    {   
        this.removeTableUpdateListener();
        
        TableModel.setRowCount( 0 );
        
        TableModel.setColumnCount( 0 );
        
        TableAttModel.setRowCount( 0 );
        
        TableForeignKeyModel.setRowCount( 0 );
        
        TriggerTableModel.setRowCount( 0 );
        
    }// func ends
    
    public void setValues( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table table )
    {
       Title = table.getName();
       org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute[] Atts = table.getAttributes();
        
       try{           
       // fill atts
       for( int i = 0; i<Atts.length; i++)
       {
           Object[] NewRow = new String[6];
           NewRow[0] = Atts[i].getAttName();
           NewRow[1] = Atts[i].getAttType();
           NewRow[2] = Atts[i].getAttKey();
           NewRow[3] = String.valueOf ( Atts[i].getAttSize() );
           NewRow[4] = String.valueOf ( true );
           NewRow[5] = "";
          
           TableAttModel.addRow( NewRow );       
           TableModel.addColumn( Atts[i].getAttName() );       
       }// for ends
       
       for( int i=0;i< table.getRowCount(); i++)
       {
          String [] row = table.returnRow( i );         
         // this.isRefresh = true;
          TableModel.addRow( row );
       }
      
       this.setForeignKeys( table.getForeignKeys() );
       
       try{
           
           if( table.getTriggers() != null ){
       for( int i=0 ;i< table.getTriggers().length; i++ )
       this.addTrigger( table.getTriggers()[i] );
           }// if ends
       }
       catch( Exception e ){
           System.out.println( "error while adding trigger " + e );
       }
       this.addTableUpdateListener();
      }
       catch( Exception e)
       {
       System.out.println( "error in setval"+e );
       }
        
       
    }// func ends
    
    private void setForeignKeys( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.ForeignKeyInterface [] ForKey ){
        
        if( ForKey.length < 1 )
            return;
        
        final int FOREIGN_KEY_COLLS = 8; // see here IMPORTANT
        for( int i=0 ; i< ForKey.length; i++ ){
           Object[] newrow = new Object[ FOREIGN_KEY_COLLS ];
           newrow[ 0 ] = ForKey[i].getAttName();
           newrow[1] = ForKey[i].getPk_Database();
           newrow[2] = ForKey[i].getPk_Table();
           newrow[3] = ForKey[i].getPK_Name();
           newrow[4 ] = ForKey[i].getDelete_Rule();
           newrow[5 ] = ForKey[i].getUpdate_Rule();
           newrow[6 ] = ForKey[i].getDeferability_Rule();
           newrow[7 ] = "";
           this.TableForeignKeyModel.addRow( newrow );
        }        
    }// func ends
    
    private boolean refresh()
   {
        //1. select its database
            this.Engine.selectDatabase( this.DatabaseNm );
            
       // 1. get domain object of table
        org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Table Table = Engine.getDatabaseReader().readTable( this.getTableName() , this.DatabaseNm );
               
        // 2. set values
         if( Table != null )
                 {
                this.setValues( Table );                         
                return true;
                }
                 else
                 {
                  // do nothing                     
                  System.out.println( "Table doesnt exist is null" );
                  return false; 
                 }
        
   }// func ends
    
    public boolean initialize()
    {
        return this.refresh();
    }// func ends
    
    public boolean reinitialize()
    {
        this.resetTable();
        return this.refresh();
    }// func ends
    
    /**
     * method for setting backend for this from manager frame
     */
    
    public void setEngine( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd eng )
    {
        Engine = eng;
    }

    public int getAttTableCollIndex ( String CollName )
    {
        for( int i=0;i<AttTable.getColumnCount(); i++)
        {
            if( CollName.equals( AttTable.getColumnName( i ) ) )
            {
                return i;
            }
        }
        // else
        return -1;
    }
    
    
     /**
     * method for table  interface
     */

    public String[] returnCollumnNames() {
        
        String [] CollNm = new String[ AttTable.getRowCount() ];
        
        for( int i=0;i<CollNm.length;i++)
        {
            CollNm[i] = ( String ) AttTable.getValueAt( i, this.getAttTableCollIndex( "Field" ) );
        }
        
        return CollNm;
    }// func ends
    
      public String getTableName()
    {
        return Title;
    }// func ends
      
      public String[] returnCollumnTypes()
      {
          String [] CollType = new String[ AttTable.getRowCount() ];
         
          for( int i=0;i<CollType.length;i++)
        {
            CollType[i] = ( String ) AttTable.getValueAt( i, this.getAttTableCollIndex("Type") );
        }
          
          return CollType;
      }// func ends
      
       public Object[][] returnTableData()
       {
           return null;
       }// func ends
       
       public String[] returnPrimaryKeys()
       {
           
           java.util.ArrayList temp = new java.util.ArrayList();
           String[] att = this.returnCollumnNames();
           for( int i=0; i< AttTable.getRowCount();i++)
           {
               if ( AttTable.getValueAt( i, this.getAttTableCollIndex("Key")).equals( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.TableAttribute.PRIMARY_KEY ) )
                   temp.add( att[i] );
           }
           
           String[] PrimKeys = new String[ temp.size() ];
           
           for( int i=0; i<PrimKeys.length; i++ )
               PrimKeys[i] = ( String ) temp.get( i );
           
           return PrimKeys;
           
       }// func ends
       
       public String[] returnForeignKeys()
       {
           int ForKeyno = 0;
           String[] ForKeys = new String[ ForKeyno ];
           
           return ForKeys;
       }// func ends
       
		public String returnCollType( String CollNm ){
		String [] CollType = this.returnCollumnTypes();
		String [] CollName = this.returnCollumnNames();
		
		for( int i=0;i <CollType.length;i++ )
			if( CollName[i].equals(CollNm) )
				return CollType[i];
		
		return null;// not found
		}
	
		public String returnCollSize( String CollNm ){
		for( int i=0; i< AttTable.getRowCount(); i++){
			if( CollNm.equals( getAttTableCollIndex("Field") ) )
				return (String) AttTable.getValueAt( i, this.getAttTableCollIndex("Size") );
		}
		return null;
		}
	
		public boolean isPrimaryKey( String CollNm ){
		
		String[] Prim = this.returnPrimaryKeys();
		
		for( int i=0;i <Prim.length;i++ )
			if( Prim[i].equals(CollNm) )
				return true;
		
		return false;
		}
	
		public boolean isForeignKey( String CollNm ){
		return false;
		} 
		
		public boolean isNullSupported( String CollNm ){
		
		for( int i=0; i< AttTable.getRowCount(); i++){
			if( CollNm.equals( (String) AttTable.getValueAt( i,getAttTableCollIndex("Field") ) ) )
				return ( (String)AttTable.getValueAt( i, this.getAttTableCollIndex("Null") ) )
                                .equals("true") ;
		}
		return false;// unexpectedy 
		}
     /**
     * method for table  interface ends
     */

    /**
     * method for table changed interface
     */
    
      public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [] getChangedTuple(){
          
          // getprim keys
          String[] pks = this.returnPrimaryKeys();
        
          // create the return tuples
          org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [] Tp= null;
          System.out.println( "\n\n "); 
          // check primary key no
          if( pks.length > 0 ){          
          Tp = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [ pks.length ];
         
          for( int i=0;i<Tp.length;i++)
          {
              Tp[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple( (String) Table.getValueAt( Table.getSelectedRow(),this.getCollumnNo( pks[i] ) )  , pks[i]  ); 
          }
         
          } // if ends
          
          else{
              
              Tp = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [ this.returnCollumnTypes().length ];
              System.out.println( "this is length"+Tp.length);
              for( int i =0 ;i<Tp.length; i++ ){
              
                  String CollNm = this.returnCollumnNames()[i];
                  
                  String temp1 = (String) Table.getValueAt( Table.getSelectedRow(), this.getCollumnNo( CollNm  ) ) ;                  
                  
                  Tp[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple( temp1, CollNm ); 
              }
          }
           System.out.println( "\n\n ");
          return Tp;
      }
    
      public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [] getInsertedValues(){
          return InsertedValues;
      }
         
      
      /**
       *  for this iteration only a single val of a row will be updated at a time for some implementarion reasons.
       * reason:: no listener for collumn update as a whole as i havent found any.
       */      
      public org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple []  getUpdatedValues(){
          
          org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple[] Tp = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple[1];
          
          Tp[0] = UpdatedVal;
          
          return Tp;
          
      }
        
      
    /**
     * method for table changed interface ends
     */
    
    
      public void setInsertedValues( Object[] Values ){
          
          String[] Type = this.returnCollumnNames();
          String[] val = new String [ Values.length ];
          
          InsertedValues = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [ Values.length ];
          
          for( int i=0;i<Values.length; i++)
              InsertedValues[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple ( (String) Values[i] , Type[i] );
          
      }
      
      public void setParent( org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame p )
      {
          parent = p;
      }// func ends
      
      private int getCollumnNo( String CollNm )
      {
          try{
          for( int i=0; i<Table.getColumnCount(); i++)
              if( Table.getColumnName(i).equals( CollNm ) )
                  return i;
          }
          catch( Exception e)
          {
              System.out.println( " exception "+ e+" occered in getCollNo" );
          }
          return -1;
      }// func ends
    
      private void removeTableUpdateListener()
      {
          try{            
              javax.swing.ListSelectionModel rowSM = Table.getSelectionModel();
              
              rowSM.removeListSelectionListener( this.TableListListener );
             
              TableModel.removeTableModelListener( TableModel.getTableModelListeners()[0] );
          }
          catch( Exception e )
          {
              System.out.println( e + " while removing the update listener...");
          }
      }// func ends
    
    /**
     *  Code for adding table listerner ot Table for update event of data in table by user.
     */
    private void addTableUpdateListener()
    {
        
        Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
            javax.swing.ListSelectionModel rowSM = Table.getSelectionModel();
            
            // adding row listener
            rowSM.addListSelectionListener( TableListListener = new javax.swing.event.ListSelectionListener() {
                public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                  
                    //Ignore extra messages.
                    if (e.getValueIsAdjusting()) return;
                  
                  //  setold((String)Table.getValueAt(Table.getSelectedRow(),Table.getSelectedColumn()));
                    
                    /**
                     * whenever any row is selected, it will be the selected tuple. 
                     * this has been done especially for update event on data.
                     */
                    // BEWARE OF THE BELOW CODE IT WILL BE CALLED WHEN DATA IS ADDED
                    
                    
                   // if( !(  e.getFirstIndex() < e.getLastIndex() ) ) {
                    // System.out.println( " \n\ttuple is being selected\n making refresh false" );
                    // isRefresh = false;
                    setTableSelectedTuple();
                    //}
                }
            });
 // no collumn selection necessary now.
            
      
            Table.getModel().addTableModelListener( 
                    new javax.swing.event.TableModelListener() {
     
           public void tableChanged(javax.swing.event.TableModelEvent e) {
              /** if( e.getAttType() == e.DELETE)
                   System.out.println( " delete was being done");
               else*/
           if( e.getType() == e.UPDATE ){
               System.out.println( "update was done & calling the ontableupdate func and is it editing?"  + state);
               state = false;
             //  if( ! isRefresh )               
               OnTableValueUpdate();
           }
    }
    } );
    }// func ends
    private boolean state = false;
    /**
     * this is the code responsible for updating the value for this panel
     */
    private void OnTableValueUpdate()
    {        
  
        setUpdatedValue(                 
                       new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple( (String)Table.getValueAt(Table.getSelectedRow(),Table.getSelectedColumn()) , Table.getColumnName( Table.getSelectedColumn() ) ) 
                        );
        String Mess = Engine.updateTableData( this ) ;
        if ( Mess ==  org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.QueryExecuter.EXECUTE_SUCCESS )
        {
        javax.swing.JOptionPane.showMessageDialog(this, "Table Value was Updated" );
        }
        else
        {
            this.reinitialize();
            javax.swing.JOptionPane.showMessageDialog(this, org.edu.gces.s2005.projects.frontendformysql.ui.Components.DisplayMessageParser.returnParsedMessage(Mess ),"Table Update Failure", javax.swing.JOptionPane.ERROR_MESSAGE  );
            
        }
        
    }// func ends
    
     private void setTableSelectedTuple( ){
               
          // getprim keys
          String[] pks = this.returnPrimaryKeys();
          
          if( Table.getSelectedRow() == -1)
          {
              System.out.println( " error\nreturning..." );
              return;
          }
          // check primary key no
          if( pks.length > 0 ){          
          TableSelectedTuple = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [ pks.length ];
          
          for( int i=0;i< TableSelectedTuple.length;i++)
          {
              try{
              //System.out.println(" this is row "+ Table.getSelectedRow() );
              TableSelectedTuple[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple( (String) Table.getValueAt( Table.getSelectedRow(),i)  , pks[i]  ); 
              }
              catch( Exception e3)
              {
                  System.out.println( e3 + "inside ");
              }
          }
          
          } // if ends
          
          else{
              try{
                  System.out.println("this array length is ::"+this.returnCollumnTypes().length);
              TableSelectedTuple = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple [ this.returnCollumnTypes().length ];
              for( int i =0 ;i< TableSelectedTuple.length; i++ ){
                  System.out.print( "row is ::"+ Table.getSelectedRow());
                  String v= (String) Table.getValueAt( Table.getSelectedRow(),i);
                  String t= this.returnCollumnNames()[i] ;
                  if( v!= null && t!= null)
                  TableSelectedTuple[i] = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple( v  ,t ); 
              }
              }
              catch( Exception e)
              {
              System.out.println(e + " in setTablesel");
              }
          }       
      }
     
       private void setUpdatedValue( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple Val )
      {
                UpdatedVal = Val;
      }
     
       
       /**
        * codes for implementing transaction listener interface.
        */
        public void onTransactionAdded( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction Transac ){
            // do nothing since this event is of no intrest to table
        }
    
        public void onTransactionCommited( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction[] CommittedTransac, java.sql.Savepoint Sp ){
            this.reinitialize();
        }
    
        public void onTranactionRollbacked( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction[] RollbackedTransac, java.sql.Savepoint Sp ){
            this.reinitialize();
        }
    
        public void onSavePointAdded( java.sql.Savepoint AddedSp ){
            // do nothing since this event is of no intrest to table
        }
    
        public void onSavePointRealeased( java.sql.Savepoint ReleasedSp ){
            // do nothing since this event is of no intrest to table
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataBtn;
    private javax.swing.JButton AttAddBtn;
    private javax.swing.JTable AttTable;
    private javax.swing.JButton DelDataBtn;
    private javax.swing.JButton DelTableAttBtn;
    private javax.swing.JTable ForeignKey;
    private javax.swing.JButton ForeignKeyDropBtn;
    private javax.swing.JCheckBox LimitCheck;
    private javax.swing.JTextField LimitIP;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JTable Table;
    private javax.swing.JButton TrigAddBtn;
    private javax.swing.JButton TrigDropBtn;
    private javax.swing.JButton TrigEditBtn;
    private javax.swing.JButton TrigRefreshBtn;
    private javax.swing.JTable TrigTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
    
    // added variables start
    private javax.swing.table.DefaultTableModel TableModel = null;//new org.edu.gces.s2005.projects.frontendformysql.ui.Components.DataTableModel();
    private javax.swing.table.DefaultTableModel TableAttModel = null;
    private javax.swing.table.DefaultTableModel TableForeignKeyModel = null;
    private org.edu.gces.s2005.projects.frontendformysql.ui.parent.MainFrame parent;
    private javax.swing.table.DefaultTableModel TriggerTableModel = null;
    
    // some data var's    
    private String Title= null; // titile of this component viz name of table it represents
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd  Engine = null; // inner back end 
    private String DatabaseNm = null; // set by the creater    
    private javax.swing.event.ListSelectionListener TableListListener = null;
    
    // added variables end
    
    // values for interface
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple[] InsertedValues = null;        
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple[] TableSelectedTuple = null;
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Tuple UpdatedVal = null;
    
    
    
    /**
     * This is the editor class for this panel 
     */
    class Editor{
        
        public void find(){
            FindWord = javax.swing.JOptionPane.showInputDialog(" Input the find word");
            
        }
        
        private void selectAll(){
            javax.swing.JTable t = this.getSelectedTable();
            if( t != null )
            this.selectAll( t );
        }
        
        private void iterativeFind( javax.swing.JTable Tb ){
            for( int i=0 ;i< Tb.getRowCount(); i++ ){
                for( int j = 0; j< Tb.getColumnCount(); j++ ){
                    //if( Tb.getValueAt(i, j ).toString().equalsIgnoreCase( this.FindWord )){
                        // stop n show
                      //  Tb.se
                    }
                }
            }
        
        
    
        private void selectAll( javax.swing.JTable T ){
            T.selectAll();
        }
        
        private javax.swing.JTable getSelectedTable(){
            if( MainTab.getSelectedIndex() == 0 ){
                return Table;
            }
            else
                if( MainTab.getSelectedIndex() == 1 ){
                return AttTable;
                }
                else
                    if( MainTab.getSelectedIndex() == 2 ){
                    return ForeignKey;
                    }
                    else
                        if( MainTab.getSelectedIndex() == 3 ){
                        return TrigTable;
                        }
            
            return null;
        }
        
        private String FindWord = null;
    }
    
}
