
//                              !! RAM !!

/**
 * DriverPanel.java
 *
 * Created on February 11, 2008, 12:47 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components;

/***
 *
 * @author  Sumit Shrestha
 */
public class DriverInfoPanel extends javax.swing.JPanel {
    
    /*** Creates new form DriverPanel */
    public DriverInfoPanel( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine ) {
        this.Engine = Engine;
        initComponents();        
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        DriverName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jdbcCheck = new javax.swing.JCheckBox();
        DefaultDriverCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        DriverJarFileName = new javax.swing.JTextField();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        DatabaseServerName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        DatabaseServerURL = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        DatabaseSeverPortNo = new javax.swing.JTextField();
        EditCheck = new javax.swing.JCheckBox();
        UpdateBtn = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Driver Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        DriverName.setEditable(false);
        DriverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Driver Name");

        jdbcCheck.setSelected(true);
        jdbcCheck.setText("JDBC");
        jdbcCheck.setEnabled(false);

        DefaultDriverCheck.setText("Default Driver");
        DefaultDriverCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultDriverCheckActionPerformed(evt);
            }
        });

        jLabel5.setText("Driver File Name");

        DriverJarFileName.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jdbcCheck, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DriverName, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(DefaultDriverCheck)
                    .addComponent(DriverJarFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DriverJarFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdbcCheck)
                    .addComponent(DefaultDriverCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Database Server", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Database Server Name");

        DatabaseServerName.setEditable(false);
        DatabaseServerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseServerNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Database Server URL");

        DatabaseServerURL.setEditable(false);
        DatabaseServerURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseServerURLActionPerformed(evt);
            }
        });

        jLabel4.setText("Port No");

        DatabaseSeverPortNo.setEditable(false);
        DatabaseSeverPortNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseSeverPortNoActionPerformed(evt);
            }
        });

        EditCheck.setText("Edit");
        EditCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCheckActionPerformed(evt);
            }
        });

        UpdateBtn.setText("UPDATE");
        UpdateBtn.setEnabled(false);
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(EditCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatabaseServerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(DatabaseSeverPortNo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(DatabaseServerURL, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(UpdateBtn))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DatabaseServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatabaseServerURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(DatabaseSeverPortNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(EditCheck)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBtn)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DriverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriverNameActionPerformed

    private void DatabaseServerURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseServerURLActionPerformed
        this.Engine.renameDriverServerURL( this.DriverID, this.DatabaseServerURL.getText() );
    }//GEN-LAST:event_DatabaseServerURLActionPerformed

    private void DatabaseSeverPortNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseSeverPortNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseSeverPortNoActionPerformed

    private void DatabaseServerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseServerNameActionPerformed
        this.Engine.renameDriverServerName( this.DriverID, this.DatabaseServerName.getText() );
    }//GEN-LAST:event_DatabaseServerNameActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        this.Engine.renameDriverServerName( this.DriverID, this.DatabaseServerName.getText() );
        this.Engine.renameDriverServerURL( this.DriverID, this.DatabaseServerURL.getText() );
        this.makeUnEditable();
}//GEN-LAST:event_UpdateBtnActionPerformed

    private void DefaultDriverCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultDriverCheckActionPerformed
        //System.out.println( "default driver action performed of "+ this.DriverName.getText() );
        if( ! this.DefaultDriverCheck.isSelected() ){            
            this.DefaultDriverCheck.setSelected( true );
            return; // initially set n user wants to remove default check
        }
        
        final String mess = this.Engine.setDefaultDriver( this.DriverID );
        if( mess != org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DriverModule.DriverManagerInterface.DefaultDriverSetSuccess ){
            this.DefaultDriverCheck.setSelected( false );
            javax.swing.JOptionPane.showMessageDialog( this, mess, "Error in serring default driver!!", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_DefaultDriverCheckActionPerformed

    private void EditCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCheckActionPerformed
        if( this.EditCheck.isSelected() )
            this.makeEditable();
        else
            this.makeUnEditable();
}//GEN-LAST:event_EditCheckActionPerformed
        
    
    public void setDriverName( String DrvName ){
        if( DrvName != null )
            this.DriverName.setText(DrvName);
    }
    
    public void setDriverJarFileName( final String DriverJarFileName ){
        this.DriverJarFileName.setText(DriverJarFileName);
    }
    
    public void setDriverServerName( String D ){
        if( D != null )
            this.DatabaseServerName.setText(D);
    }
    
    public void setDriverServerURL( String URL ){
        if( URL != null )
            this.DatabaseServerURL.setText(URL);
    }
    
    public void setDriverServerPortNo( String PtNO){
        if( PtNO != null )
            this.DatabaseSeverPortNo.setText(PtNO);
    }
    
    public void setJDBCCompliantCheck( java.sql.Driver Drv ){
        if( Drv != null )
        this.jdbcCheck.setSelected( Drv.jdbcCompliant() );
    }
    
    public void setDriverInfo( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Driver D ){
       this.DriverID = D.getDriverID();
       this.setDriverName( D.getDriverName() );
       this.setDriverServerName( D.getDatabaseServerName());
       this.setDriverServerURL( D.getDatabaseServerURL() );
       this.setDriverServerPortNo( D.getDatabaseServerPortNo() );
       this.setJDBCCompliantCheck( D.getDriver() );
       this.setDriverJarFileName( D.getDriverJarFileName() );
    }
    
    public void setDefault( boolean state ){
        this.DefaultDriverCheck.setSelected(state);
    }
    
    public void makeEditable(){
        this.DatabaseServerName.setEditable( true );
        this.DatabaseServerURL.setEditable( true );
        this.UpdateBtn.setEnabled( true );
    }
    
    public void makeUnEditable(){
        this.DatabaseServerName.setEditable( false );
        this.DatabaseServerURL.setEditable( false );
        this.UpdateBtn.setEnabled( false );
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DatabaseServerName;
    private javax.swing.JTextField DatabaseServerURL;
    private javax.swing.JTextField DatabaseSeverPortNo;
    private javax.swing.JCheckBox DefaultDriverCheck;
    private javax.swing.JTextField DriverJarFileName;
    private javax.swing.JTextField DriverName;
    private javax.swing.JCheckBox EditCheck;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jdbcCheck;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.BackEnd Engine = null;        
    private String DriverID ;// this is the ID as set internally by the system
}
