
//                         !! RAM !!


/**
 * ResultSetViewer.java
 *
 * Created on October 17, 2007, 5:09 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components;


/***
 *
 * @author  sumit
 */
public class ResultSetViewer extends javax.swing.JDialog {
    
    /*** Creates new form ResultSetViewer */
    public ResultSetViewer( java.awt.Frame parent , java.sql.ResultSet r ) {
        super(parent, false );
        this.rs = r;
        initComponents();        
        this.analyze();  
        this.addWarnings();
        super.pack();
        super.setLocationRelativeTo( null );
        super.setVisible( true );        
        this.OKBtn.requestFocusInWindow();
    }
    
    public ResultSetViewer( java.awt.Frame parent ){
        super( parent, false );
        this.initComponents();
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel2;
        javax.swing.JScrollPane jScrollPane1;
        javax.swing.JScrollPane jScrollPane2;
        javax.swing.JTabbedPane jTabbedPane1;

        jPanel1 = new javax.swing.JPanel();
        OKBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        WarningTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Database Result Viewer");
        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });
        OKBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OKBtnKeyTyped(evt);
            }
        });

        jPanel1.add(OKBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        ResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        this.ResultTableModel = ( javax.swing.table.DefaultTableModel ) this.ResultTable.getModel();
        jScrollPane1.setViewportView(ResultTable);

        jTabbedPane1.addTab("Result Table", null, jScrollPane1, "gives the resulted table values");

        jPanel2.setLayout(new java.awt.BorderLayout());

        WarningTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Warning"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        WarningTableModel = ( javax.swing.table.DefaultTableModel ) WarningTable.getModel();
        jScrollPane2.setViewportView(WarningTable);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Warnings", null, jPanel2, "gives the warnings during operation");

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OKBtnKeyTyped
        this.disposeWindow();
    }//GEN-LAST:event_OKBtnKeyTyped

    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        this.disposeWindow();
    }//GEN-LAST:event_OKBtnActionPerformed
    
    private void analyze(){
        this.addColls();
        this.addRows();
    }
    
    /**
     * called when the window is disabled
     */
    private void resetDisplay(){
       this.ResultTableModel.setRowCount( 0 );
       this.ResultTableModel.setColumnCount( 0 );
       
       this.WarningTableModel.setRowCount( 0 );
       this.WarningTableModel.setColumnCount( 0 );
    }
    
    private void addColls(){
        try{
        java.sql.ResultSetMetaData rmd = rs.getMetaData();
        int coll = rmd.getColumnCount();
        if( coll < 1 ){ // no result
            super.setTitle( super.getTitle() + " NO RESULT!! ");
            return;
        }
        
        for( int i=0 ;i<coll; i++ ){
            this.ResultTableModel.addColumn( rmd.getColumnLabel( i + 1 ) );
        }               
        }
        catch( Exception e){
            System.out.println( "error! " + e + "while adding collumns");
            this.disposeWindow();
            super.dispose();
        }
    }
    
    public void addRows(){
        try{
             while(rs.next()){  
              String [] Array = new String[ this.ResultTableModel.getColumnCount() ];
	      for( int i= 0 ; i< Array.length ; i++){
              Array[i] =  rs.getString( i + 1 );	      
		  }		  
              this.ResultTableModel.addRow( Array );
            }
        }
        catch( Exception e){
            System.out.println( "error while adding rows" );
        }
    }
    
    public void addWarnings(){
        try{
        java.sql.SQLWarning warn = rs.getWarnings();
        
        int i =1;
        while( warn != null ){
            String array[] = new String[2];
            array[0] = String.valueOf( i );
            array[1] = warn.getMessage();
            this.WarningTableModel.addRow( array );
            i++;
        }
        
        }
        catch( Exception e ){
            System.out.println(" error while adding warnings"+ e );
        }
    }
    
    
    public void displayResultSet( java.sql.ResultSet Rs ){
        this.rs = Rs;
        this.analyze();  
        this.addWarnings();
        super.pack();
        if( this.OKBtn == null){
            System.out.println( "ok btn is null returning..." );
            return;
        }
        this.OKBtn.requestFocusInWindow();
        super.setLocationRelativeTo( null );        
        super.setVisible( true );                
    }
    
    private void disposeWindow(){
        this.resetDisplay();
        this.setVisible( false );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKBtn;
    private javax.swing.JTable ResultTable;
    private javax.swing.JTable WarningTable;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel ResultTableModel = null;
    private javax.swing.table.DefaultTableModel WarningTableModel = null;
    private java.sql.ResultSet rs = null;
}
