
//                        !! RAM !!

/**
 * StatusBar.java
 *
 * Created on October 23, 2007, 9:32 AM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components;


import java.awt.event.ActionEvent;

/***
 *
 * @author  sumit
 */
public class StatusBar extends javax.swing.JPanel {
    
    /*** Creates new form StatusBar */
    public StatusBar() {
        initComponents();
        this.onLastReach();
        this.onRecentReach();
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        PreviousBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        StatusText = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null)));
        setToolTipText("Status Bar");
        PreviousBtn.setText("<<");
        PreviousBtn.setToolTipText("view previous status");
        PreviousBtn.setMinimumSize(new java.awt.Dimension(30, 18));
        PreviousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousBtnActionPerformed(evt);
            }
        });

        add(PreviousBtn, java.awt.BorderLayout.WEST);

        NextBtn.setText(">>");
        NextBtn.setToolTipText("view Next Status");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        add(NextBtn, java.awt.BorderLayout.EAST);

        StatusText.setFont(new java.awt.Font("Monospac821 BT", 0, 10));
        add(StatusText, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        this.setNextStatus();
    }//GEN-LAST:event_NextBtnActionPerformed

    private void PreviousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousBtnActionPerformed
        this.setPreviousStatus();
    }//GEN-LAST:event_PreviousBtnActionPerformed
    
    public void setStatus( String state ){
        this.StatusList.setStatus( state );
        this.StatusText.setText( state );
        
        this.onRecentReach();
        if( ! this.StatusList.reachedMostPrevious() )
        this.onNotPreviousReach();        
    }
    
    public void resetStatus(){
        this.StatusList.resetStatus();
        this.StatusText.setText( "" );
        
        this.onRecentReach();
        if( ! this.StatusList.reachedMostPrevious() )
        this.onNotPreviousReach();        
    }
    
    
    public void addStatus( String state ){
        this.StatusText.setText( this.StatusList.addStatus( state ) );
        
        this.onRecentReach();
        if( ! this.StatusList.reachedMostPrevious() )
        this.onNotPreviousReach();        
    }
           
    private void setPreviousStatus(){        
        try{
            String State = this.StatusList.getPreviousStatus();
            if( State != this.StatusList.NO_PREVIOUS ){
                this.StatusText.setText( State );           
            
                this.onNotRecentReach();
                if( this.StatusList.reachedMostPrevious() ){
                    this.onLastReach();
                }
            }
        }
        catch( java.lang.IndexOutOfBoundsException e ){            
        }                
    }
    
    private void setNextStatus(){        
        try{
            String State = this.StatusList.getNextStatus();
            if( State != this.StatusList.NO_NEXT ){
                this.StatusText.setText( State );
            
                this.onNotPreviousReach();
                if( this.StatusList.reachedFirstMostRecent() )
                    this.onRecentReach();
            }
        }
        catch( java.lang.IndexOutOfBoundsException e ){            
        }
    }
    
            
    /**
     * code for enabling n disabling buttons
     */
    
    /**
     * 4 event of reaching the most previous or least recent state
     */
    private void onLastReach(){
       this.PreviousBtn.setEnabled( false ); 
    }
    
    /**
     * 4 event of reaching the most recent state
     */
    private void onRecentReach(){
        this.NextBtn.setEnabled( false );
    }   
    
    /**
     * 4 event of not reaching last
     */
    private void onNotPreviousReach(){
        this.PreviousBtn.setEnabled( true );        
    }            
    
    /**
     * 4 event of not reaching recent
     */
    private void onNotRecentReach(){
        this.NextBtn.setEnabled( true );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextBtn;
    private javax.swing.JButton PreviousBtn;
    private javax.swing.JLabel StatusText;
    // End of variables declaration//GEN-END:variables
    
    // fields for inner implementation
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DataStructures.StatusBarDataStructure StatusList = new org.edu.gces.s2005.projects.frontendformysql.domain.BackEndComponent.DataStructures.StatusBarDataStructure( 20 );
    
    
    
    public static void main( String[] a ){
        final org.edu.gces.s2005.projects.frontendformysql.ui.Components.StatusBar bar = new org.edu.gces.s2005.projects.frontendformysql.ui.Components.StatusBar( );
        javax.swing.JFrame f= new javax.swing.JFrame();
        f.setDefaultCloseOperation( javax.swing.JFrame.EXIT_ON_CLOSE );
        f.setLayout( new java.awt.BorderLayout() );
        
        javax.swing.JPanel p = new javax.swing.JPanel( new java.awt.FlowLayout() );
        javax.swing.JButton btn = new javax.swing.JButton("press 4 set status ");
        javax.swing.JButton btn1 = new javax.swing.JButton("press 4 add status ");
        javax.swing.JButton btn2 = new javax.swing.JButton("press 4 reset status ");
        p.add( btn );
        p.add( btn1 );
        p.add( btn2 );
        btn.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                bar.setStatus( "this is the status ");
            }
        });
        
        btn2.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                bar.resetStatus();
            }
        });
        
        btn1.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                bar.addStatus( "AddedStatus" );
            }
        });
        f.add( bar, java.awt.BorderLayout.SOUTH );
        f.add( p );
        f.setSize( 100,100);
        f.setVisible( true );
    }
            
}
