
//                          !! RAM !!

/**
 * TransactionStateViewer.java
 *
 * Created on November 2, 2007, 3:10 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components;

/***
 *
 * @author  sumit
 */
public class TransactionStateViewer extends javax.swing.JDialog {
    
    /*** Creates new form TransactionStateViewer */
    public TransactionStateViewer(java.awt.Frame parent, org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.TransactionManager TransacMan ) {
        super(parent, true );
        this.TransacMan = TransacMan;
        initComponents();
        this.initialize();
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        SuppSavePt = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        SuppQueryTpCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        AutoCommCheck = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        IsolationCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction State");
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Transaction Support Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        SuppSavePt.setText("Supports Save Points");
        SuppSavePt.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        SuppSavePt.setEnabled(false);
        SuppSavePt.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel1.setText("Supported Query Type");

        SuppQueryTpCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DDL Only", "DDL And DML" }));
        SuppQueryTpCombo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SuppSavePt)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuppQueryTpCombo, 0, 196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuppSavePt)
                    .addComponent(jLabel1)
                    .addComponent(SuppQueryTpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Transaction State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);
        AutoCommCheck.setText("Auto Commit");
        AutoCommCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        AutoCommCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AutoCommCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoCommCheckActionPerformed(evt);
            }
        });

        jLabel2.setText("Isolation Type");

        IsolationCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRANSACTION_READ_UNCOMMITTED", "TRANSACTION_READ_COMMITTED", "TRANSACTION_REPEATABLE_READ", "TRANSACTION_SERIALIZABLE", "TRANSACTION_NONE" }));
        IsolationCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IsolationComboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AutoCommCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IsolationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoCommCheck)
                    .addComponent(jLabel2)
                    .addComponent(IsolationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsolationComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IsolationComboItemStateChanged
        if( ! this.TransacMan.setCurrentIsolationType( this.IsolationCombo.getSelectedItem().toString() ) )
            javax.swing.JOptionPane.showMessageDialog( null, "Isolation type not set" );
    }//GEN-LAST:event_IsolationComboItemStateChanged

    private void AutoCommCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoCommCheckActionPerformed
        if( this.AutoCommCheck.isSelected() )
            this.TransacMan.setAutoCommit();
        else
            this.TransacMan.removeAutoCommit();
    }//GEN-LAST:event_AutoCommCheckActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible( false );
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * method to initialize other things. must be called after initializing transc man.
     */
    private void initialize(){
        
        if( this.TransacMan == null ){
            return ;
        }
        
        // else
        this.SuppSavePt.setSelected( this.TransacMan.supportsSavePoints() );
        
        this.SuppQueryTpCombo.setSelectedIndex( this.TransacMan.supportsDDLOnly()? 0: 1 );
        
        this.AutoCommCheck.setSelected( this.TransacMan.isAutoCommit() );
        
        this.IsolationCombo.setSelectedItem( this.TransacMan.getCurrentIsolationType() );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AutoCommCheck;
    private javax.swing.JComboBox IsolationCombo;
    private javax.swing.JComboBox SuppQueryTpCombo;
    private javax.swing.JCheckBox SuppSavePt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.TransactionManager TransacMan = null;
}
