
//                       !! RAM !!

/**
 * TransactionHistoryWindow.java
 *
 * Created on November 1, 2007, 1:11 PM
 */

package org.edu.gces.s2005.projects.frontendformysql.ui.Components;

/***
 *
 * @author  sumit
 */
public class TransactionHistoryWindow extends javax.swing.JDialog implements org.edu.gces.s2005.projects.frontendformysql.domain.BackEndInterfaces.TransactionListener {
    
    /*** Creates new form TransactionHistoryWindow */
    public TransactionHistoryWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // code for column formating
        this.HistoryTable.getColumnModel().getColumn( 0 ).setPreferredWidth( 1 );
        this.HistoryTable.getColumnModel().getColumn( 1 ).setPreferredWidth( 150 );
        this.HistoryTable.getColumnModel().getColumn( 2 ).setPreferredWidth( 40 );
        
        super.setLocationRelativeTo( null );
    }
    
    /*** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RollBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction History");
        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Events", "SavePoint"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        this.HistoryTableModel = ( javax.swing.table.DefaultTableModel ) this.HistoryTable.getModel();

        jScrollPane1.setViewportView(HistoryTable);

        jButton1.setText("--");
        jButton1.setToolTipText("Remove SavePoint");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("++");
        jButton2.setToolTipText("Set Current Save Point");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        RollBackBtn.setText("Rb");
        RollBackBtn.setToolTipText("Rollback to Selected Savepoint");
        RollBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RollBackBtn)
                .addContainerGap(104, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(RollBackBtn))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollBackBtnActionPerformed
        int row = this.HistoryTable.getSelectedRow();
        
        if( row < 0 )
            return;
        
        //else
        Object val = this.HistoryTable.getValueAt( row, 2 );
        
        if( val == this.NO_SavePoint ){
            javax.swing.JOptionPane.showMessageDialog( this, "No Save Point Here so Returning","No Save Point Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            return; // there was no save point created here so no realease
        }
        
        // else
        this.TransacMan.rollback( val.toString() );
        
    }//GEN-LAST:event_RollBackBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = this.HistoryTable.getSelectedRow();
        
        if( row < 0 )
            return;
        
        //else
        Object val = this.HistoryTable.getValueAt( row, 2 );
        
        if( val == this.NO_SavePoint ){
            javax.swing.JOptionPane.showMessageDialog( this, "No Save Point Here so Returning","No Save Point Error!!", javax.swing.JOptionPane.ERROR_MESSAGE );
            return; // there was no save point created here so no realease
        }
        
        // else
        this.TransacMan.releaseSavePoint( val.toString() );
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        org.edu.gces.s2005.projects.frontendformysql.ui.Forms.SavePointInputForm form = new org.edu.gces.s2005.projects.frontendformysql.ui.Forms.SavePointInputForm( null, true );
        form.setVisible( true );
        
        if( form.getState() == form.OK ){
            String Nm = form.getSavePoint();            
            final String Mess = this.TransacMan.createSavePoint( Nm );
            
            if( Mess != this.TransacMan.SAVEPOINT_CREATED ){
                javax.swing.JOptionPane.showMessageDialog( this, Mess, "Save Point Not Created", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public void setTransactionManager( org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.TransactionManager TransacMan ){
        this.TransacMan = TransacMan;
        this.TransacMan.addTransactionListener( this );
    }
    
    private void setDisplay(){
        org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction[] TransacArray = this.TransacMan.getTransactions();       
        
        // empty table contents
        this.HistoryTableModel.setRowCount( 0 );        
        
        if( TransacArray == null || TransacArray.length < 1 )
            return;
        
        for( int i=0 ;i< TransacArray.length; i++ ){
            String[] addArray = new String[ 3 ];
            
            addArray[0] = String.valueOf( i + 1 );
            addArray[1] = TransacArray[i].getName();
            
            try{
                if( TransacArray[i].getSavePoint() == null )
                    addArray[2] = this.NO_SavePoint;
                else
                    addArray[2] = TransacArray[i].getSavePoint().getSavepointName();
            }
            catch( java.sql.SQLException e ){
                addArray[2] = "";
            }
            
            this.HistoryTableModel.addRow( addArray );
        }
    }
    
    public void setVisible( boolean state ){
        if( state ){
            this.setDisplay();
        }
        
        super.setVisible( state );
    }
    
    /**
     * code for implementing listener
     */
    public void onTransactionAdded( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction Transac ){
        this.setDisplay();
    }
    
    public void onTransactionCommited( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction[] CommittedTransac, java.sql.Savepoint Sp ){
        this.setDisplay();
    }
    
    public void onTranactionRollbacked( org.edu.gces.s2005.projects.frontendformysql.domain.BackEndData.Transaction[] CommittedTransac, java.sql.Savepoint Sp ){
        this.setDisplay();
    }
    
    public void onSavePointAdded( java.sql.Savepoint AddedSp ){
        this.setDisplay();
    }
    
    public void onSavePointRealeased( java.sql.Savepoint ReleasedSp ){
        this.setDisplay();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTable;
    private javax.swing.JButton RollBackBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private org.edu.gces.s2005.projects.frontendformysql.domain.BackEnd.TransactionManager TransacMan = null;
    private javax.swing.table.DefaultTableModel HistoryTableModel = null;
    
    // some constants
    public static final String NO_SavePoint = "No Sp";
}
